<?php

use Illuminate\Database\Seeder;

class BranchesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('branches')->delete();
        
        \DB::table('branches')->insert(array (
            0 => 
            array (
                'id' => '1',
                'translation_lang' => 'en',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Agency',
                'slug' => 'agency',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            1 => 
            array (
                'id' => '2',
                'translation_lang' => 'fr',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Agency',
                'slug' => 'agency',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            2 => 
            array (
                'id' => '3',
                'translation_lang' => 'es',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Agency',
                'slug' => 'agency',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            3 => 
            array (
                'id' => '4',
                'translation_lang' => 'de',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Agentur',
                'slug' => 'agency',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            4 => 
            array (
                'id' => '5',
                'translation_lang' => 'en',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'others',
                'slug' => 'othersd',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            5 => 
            array (
                'id' => '6',
                'translation_lang' => 'fr',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'others',
                'slug' => 'othersd',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            6 => 
            array (
                'id' => '7',
                'translation_lang' => 'es',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'others',
                'slug' => 'othersd',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            7 => 
            array (
                'id' => '8',
                'translation_lang' => 'de',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'andere',
                'slug' => 'others',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            8 => 
            array (
                'id' => '9',
                'translation_lang' => 'en',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Booker',
                'slug' => 'booker',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            9 => 
            array (
                'id' => '10',
                'translation_lang' => 'fr',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Booker',
                'slug' => 'booker',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            10 => 
            array (
                'id' => '11',
                'translation_lang' => 'es',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Booker',
                'slug' => 'booker',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            11 => 
            array (
                'id' => '12',
                'translation_lang' => 'de',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Booker',
                'slug' => 'booker',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            12 => 
            array (
                'id' => '13',
                'translation_lang' => 'en',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Fashion Stylist',
                'slug' => 'fashion-stylist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            13 => 
            array (
                'id' => '14',
                'translation_lang' => 'fr',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Fashion Stylist',
                'slug' => 'fashion-stylist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            14 => 
            array (
                'id' => '15',
                'translation_lang' => 'es',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Fashion Stylist',
                'slug' => 'fashion-stylist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            15 => 
            array (
                'id' => '16',
                'translation_lang' => 'de',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Fashion Stylist',
                'slug' => 'fashion-stylist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            16 => 
            array (
                'id' => '17',
                'translation_lang' => 'en',
                'translation_of' => '17',
                'parent_id' => '0',
                'name' => 'Movie Company',
                'slug' => 'movie-company',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            17 => 
            array (
                'id' => '18',
                'translation_lang' => 'fr',
                'translation_of' => '17',
                'parent_id' => '0',
                'name' => 'Movie Company',
                'slug' => 'movie-company',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            18 => 
            array (
                'id' => '19',
                'translation_lang' => 'es',
                'translation_of' => '17',
                'parent_id' => '0',
                'name' => 'Movie Company',
                'slug' => 'movie-company',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            19 => 
            array (
                'id' => '20',
                'translation_lang' => 'de',
                'translation_of' => '17',
                'parent_id' => '0',
                'name' => 'Filmproduktion',
                'slug' => 'movie-company',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            20 => 
            array (
                'id' => '21',
                'translation_lang' => 'en',
                'translation_of' => '21',
                'parent_id' => '0',
                'name' => 'Photographer',
                'slug' => 'photographer',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            21 => 
            array (
                'id' => '22',
                'translation_lang' => 'fr',
                'translation_of' => '21',
                'parent_id' => '0',
                'name' => 'Photographer',
                'slug' => 'photographer',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            22 => 
            array (
                'id' => '23',
                'translation_lang' => 'es',
                'translation_of' => '21',
                'parent_id' => '0',
                'name' => 'Photographer',
                'slug' => 'photographer',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            23 => 
            array (
                'id' => '24',
                'translation_lang' => 'de',
                'translation_of' => '21',
                'parent_id' => '0',
                'name' => 'Fotograf',
                'slug' => 'photographer',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            24 => 
            array (
                'id' => '25',
                'translation_lang' => 'en',
                'translation_of' => '25',
                'parent_id' => '0',
                'name' => 'Hair stylist',
                'slug' => 'hair-stylist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            25 => 
            array (
                'id' => '26',
                'translation_lang' => 'fr',
                'translation_of' => '25',
                'parent_id' => '0',
                'name' => 'Hair stylist',
                'slug' => 'hair-stylist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            26 => 
            array (
                'id' => '27',
                'translation_lang' => 'es',
                'translation_of' => '25',
                'parent_id' => '0',
                'name' => 'Hair stylist',
                'slug' => 'hair-stylist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            27 => 
            array (
                'id' => '28',
                'translation_lang' => 'de',
                'translation_of' => '25',
                'parent_id' => '0',
                'name' => 'Haar stylist',
                'slug' => 'hair-stylist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            28 => 
            array (
                'id' => '29',
                'translation_lang' => 'en',
                'translation_of' => '29',
                'parent_id' => '0',
                'name' => 'Make-up artist',
                'slug' => 'makeup-artist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            29 => 
            array (
                'id' => '30',
                'translation_lang' => 'fr',
                'translation_of' => '29',
                'parent_id' => '0',
                'name' => 'Make-up artist',
                'slug' => 'makeup-artist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            30 => 
            array (
                'id' => '31',
                'translation_lang' => 'es',
                'translation_of' => '29',
                'parent_id' => '0',
                'name' => 'Make-up artist',
                'slug' => 'makeup-artist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            31 => 
            array (
                'id' => '32',
                'translation_lang' => 'de',
                'translation_of' => '29',
                'parent_id' => '0',
                'name' => 'Make-up artist',
                'slug' => 'makeup-artist',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            32 => 
            array (
                'id' => '33',
                'translation_lang' => 'en',
                'translation_of' => '33',
                'parent_id' => '0',
                'name' => 'Model scout',
                'slug' => 'model-scout',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            33 => 
            array (
                'id' => '34',
                'translation_lang' => 'fr',
                'translation_of' => '33',
                'parent_id' => '0',
                'name' => 'Model scout',
                'slug' => 'model-scout',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            34 => 
            array (
                'id' => '35',
                'translation_lang' => 'es',
                'translation_of' => '33',
                'parent_id' => '0',
                'name' => 'Model scout',
                'slug' => 'model-scout',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            35 => 
            array (
                'id' => '36',
                'translation_lang' => 'de',
                'translation_of' => '33',
                'parent_id' => '0',
                'name' => 'Model scout',
                'slug' => 'model-scout',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            36 => 
            array (
                'id' => '37',
                'translation_lang' => 'en',
                'translation_of' => '37',
                'parent_id' => '0',
                'name' => 'Company',
                'slug' => 'company',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            37 => 
            array (
                'id' => '38',
                'translation_lang' => 'fr',
                'translation_of' => '37',
                'parent_id' => '0',
                'name' => 'Company',
                'slug' => 'company',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            38 => 
            array (
                'id' => '39',
                'translation_lang' => 'es',
                'translation_of' => '37',
                'parent_id' => '0',
                'name' => 'Company',
                'slug' => 'company',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            39 => 
            array (
                'id' => '40',
                'translation_lang' => 'de',
                'translation_of' => '37',
                'parent_id' => '0',
                'name' => 'Unternehmen',
                'slug' => 'company',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            40 => 
            array (
                'id' => '41',
                'translation_lang' => 'en',
                'translation_of' => '41',
                'parent_id' => '0',
                'name' => 'Advertisment agency',
                'slug' => 'advertisment-agency',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            41 => 
            array (
                'id' => '42',
                'translation_lang' => 'fr',
                'translation_of' => '41',
                'parent_id' => '0',
                'name' => 'Advertisment agency',
                'slug' => 'advertisment-agency',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            42 => 
            array (
                'id' => '43',
                'translation_lang' => 'es',
                'translation_of' => '41',
                'parent_id' => '0',
                'name' => 'Advertisment agency',
                'slug' => 'advertisment-agency',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            43 => 
            array (
                'id' => '44',
                'translation_lang' => 'de',
                'translation_of' => '41',
                'parent_id' => '0',
                'name' => 'Werbeagentur',
                'slug' => 'advertisment-agency',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
        ));
        
        
    }
}