<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => '1',
                'translation_lang' => 'en',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Engineering',
                'slug' => 'engineering',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '203',
                'rgt' => '204',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            1 => 
            array (
                'id' => '2',
                'translation_lang' => 'en',
                'translation_of' => '2',
                'parent_id' => '0',
                'name' => 'Financial Services',
                'slug' => 'financial-services',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '197',
                'rgt' => '198',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            2 => 
            array (
                'id' => '3',
                'translation_lang' => 'en',
                'translation_of' => '3',
                'parent_id' => '0',
                'name' => 'Banking',
                'slug' => 'banking',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '195',
                'rgt' => '196',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            3 => 
            array (
                'id' => '4',
                'translation_lang' => 'en',
                'translation_of' => '4',
                'parent_id' => '0',
                'name' => 'Security & Safety',
                'slug' => 'security-safety',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '193',
                'rgt' => '194',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            4 => 
            array (
                'id' => '5',
                'translation_lang' => 'en',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'Training',
                'slug' => 'training',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '187',
                'rgt' => '188',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            5 => 
            array (
                'id' => '6',
                'translation_lang' => 'en',
                'translation_of' => '6',
                'parent_id' => '0',
                'name' => 'Public Service',
                'slug' => 'public-service',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '185',
                'rgt' => '186',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            6 => 
            array (
                'id' => '7',
                'translation_lang' => 'en',
                'translation_of' => '7',
                'parent_id' => '0',
                'name' => 'Real Estate',
                'slug' => 'real-estate',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '213',
                'rgt' => '214',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            7 => 
            array (
                'id' => '8',
                'translation_lang' => 'en',
                'translation_of' => '8',
                'parent_id' => '0',
                'name' => 'Independent & Freelance',
                'slug' => 'independent-freelance',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '205',
                'rgt' => '206',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            8 => 
            array (
                'id' => '9',
                'translation_lang' => 'en',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'IT & Telecoms',
                'slug' => 'it-telecoms',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '207',
                'rgt' => '208',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            9 => 
            array (
                'id' => '10',
                'translation_lang' => 'en',
                'translation_of' => '10',
                'parent_id' => '0',
                'name' => 'Marketing & Communication',
                'slug' => 'marketing-communication',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '223',
                'rgt' => '224',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            10 => 
            array (
                'id' => '11',
                'translation_lang' => 'en',
                'translation_of' => '11',
                'parent_id' => '0',
                'name' => 'Babysitting & Nanny Work',
                'slug' => 'babysitting-nanny-work',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '221',
                'rgt' => '222',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            11 => 
            array (
                'id' => '12',
                'translation_lang' => 'en',
                'translation_of' => '12',
                'parent_id' => '0',
                'name' => 'Human Resources',
                'slug' => 'human-resources',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '219',
                'rgt' => '220',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            12 => 
            array (
                'id' => '13',
                'translation_lang' => 'en',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Medical & Healthcare',
                'slug' => 'medical-healthcare',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '217',
                'rgt' => '218',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            13 => 
            array (
                'id' => '14',
                'translation_lang' => 'en',
                'translation_of' => '14',
                'parent_id' => '0',
                'name' => 'Tourism & Restaurants',
                'slug' => 'tourism-restaurants',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '211',
                'rgt' => '212',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            14 => 
            array (
                'id' => '15',
                'translation_lang' => 'en',
                'translation_of' => '15',
                'parent_id' => '0',
                'name' => 'Transportation & Logistics',
                'slug' => 'transportation-logistics',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '209',
                'rgt' => '210',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            15 => 
            array (
                'id' => '16',
                'translation_lang' => 'fr',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Ingénierie',
                'slug' => 'ingenierie',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '203',
                'rgt' => '204',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            16 => 
            array (
                'id' => '17',
                'translation_lang' => 'fr',
                'translation_of' => '2',
                'parent_id' => '0',
                'name' => 'Services financiers',
                'slug' => 'services-financiers',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '197',
                'rgt' => '198',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            17 => 
            array (
                'id' => '18',
                'translation_lang' => 'fr',
                'translation_of' => '3',
                'parent_id' => '0',
                'name' => 'Banque',
                'slug' => 'banque',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '195',
                'rgt' => '196',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            18 => 
            array (
                'id' => '19',
                'translation_lang' => 'fr',
                'translation_of' => '4',
                'parent_id' => '0',
                'name' => 'Sécurité & Sureté',
                'slug' => 'securite-surete',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '193',
                'rgt' => '194',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            19 => 
            array (
                'id' => '20',
                'translation_lang' => 'fr',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'Formation',
                'slug' => 'formation',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '187',
                'rgt' => '188',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            20 => 
            array (
                'id' => '21',
                'translation_lang' => 'fr',
                'translation_of' => '6',
                'parent_id' => '0',
                'name' => 'Service public',
                'slug' => 'service-public',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '185',
                'rgt' => '186',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            21 => 
            array (
                'id' => '22',
                'translation_lang' => 'fr',
                'translation_of' => '7',
                'parent_id' => '0',
                'name' => 'Immobilier',
                'slug' => 'immobilier',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '213',
                'rgt' => '214',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            22 => 
            array (
                'id' => '23',
                'translation_lang' => 'fr',
                'translation_of' => '8',
                'parent_id' => '0',
                'name' => 'Indépendants & Freelance',
                'slug' => 'independants-freelance',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '205',
                'rgt' => '206',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            23 => 
            array (
                'id' => '24',
                'translation_lang' => 'fr',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Informatique & Télécoms',
                'slug' => 'informatique-telecoms',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '207',
                'rgt' => '208',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            24 => 
            array (
                'id' => '25',
                'translation_lang' => 'fr',
                'translation_of' => '10',
                'parent_id' => '0',
                'name' => 'Marketing & Communication',
                'slug' => 'marketing-communication',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '223',
                'rgt' => '224',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            25 => 
            array (
                'id' => '26',
                'translation_lang' => 'fr',
                'translation_of' => '11',
                'parent_id' => '0',
                'name' => 'Garderie',
                'slug' => 'garderie',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '221',
                'rgt' => '222',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            26 => 
            array (
                'id' => '27',
                'translation_lang' => 'fr',
                'translation_of' => '12',
                'parent_id' => '0',
                'name' => 'Ressources humaines',
                'slug' => 'ressources-humaines',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '219',
                'rgt' => '220',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            27 => 
            array (
                'id' => '28',
                'translation_lang' => 'fr',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Médecine & Santé',
                'slug' => 'medecine-sante',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '217',
                'rgt' => '218',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            28 => 
            array (
                'id' => '29',
                'translation_lang' => 'fr',
                'translation_of' => '14',
                'parent_id' => '0',
                'name' => 'Tourisme & Restaurants',
                'slug' => 'tourisme-restaurants',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '211',
                'rgt' => '212',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            29 => 
            array (
                'id' => '30',
                'translation_lang' => 'fr',
                'translation_of' => '15',
                'parent_id' => '0',
                'name' => 'Transport et logistique',
                'slug' => 'transport-logistique',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '209',
                'rgt' => '210',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            30 => 
            array (
                'id' => '31',
                'translation_lang' => 'es',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Engineering',
                'slug' => 'engineering',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '203',
                'rgt' => '204',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            31 => 
            array (
                'id' => '32',
                'translation_lang' => 'es',
                'translation_of' => '2',
                'parent_id' => '0',
                'name' => 'Financial Services',
                'slug' => 'financial-services',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '197',
                'rgt' => '198',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            32 => 
            array (
                'id' => '33',
                'translation_lang' => 'es',
                'translation_of' => '3',
                'parent_id' => '0',
                'name' => 'Banking',
                'slug' => 'banking',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '195',
                'rgt' => '196',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            33 => 
            array (
                'id' => '34',
                'translation_lang' => 'es',
                'translation_of' => '4',
                'parent_id' => '0',
                'name' => 'Security & Safety',
                'slug' => 'security-safety',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '193',
                'rgt' => '194',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            34 => 
            array (
                'id' => '35',
                'translation_lang' => 'es',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'Training',
                'slug' => 'training',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '187',
                'rgt' => '188',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            35 => 
            array (
                'id' => '36',
                'translation_lang' => 'es',
                'translation_of' => '6',
                'parent_id' => '0',
                'name' => 'Public Service',
                'slug' => 'public-service',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '185',
                'rgt' => '186',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            36 => 
            array (
                'id' => '37',
                'translation_lang' => 'es',
                'translation_of' => '7',
                'parent_id' => '0',
                'name' => 'Real Estate',
                'slug' => 'real-estate',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '213',
                'rgt' => '214',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            37 => 
            array (
                'id' => '38',
                'translation_lang' => 'es',
                'translation_of' => '8',
                'parent_id' => '0',
                'name' => 'Independent & Freelance',
                'slug' => 'independent-freelance',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '205',
                'rgt' => '206',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            38 => 
            array (
                'id' => '39',
                'translation_lang' => 'es',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'IT & Telecoms',
                'slug' => 'it-telecoms',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '207',
                'rgt' => '208',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            39 => 
            array (
                'id' => '40',
                'translation_lang' => 'es',
                'translation_of' => '10',
                'parent_id' => '0',
                'name' => 'Marketing & Communication',
                'slug' => 'marketing-communication',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '223',
                'rgt' => '224',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            40 => 
            array (
                'id' => '41',
                'translation_lang' => 'es',
                'translation_of' => '11',
                'parent_id' => '0',
                'name' => 'Babysitting & Nanny Work',
                'slug' => 'babysitting-nanny-work',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '221',
                'rgt' => '222',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            41 => 
            array (
                'id' => '42',
                'translation_lang' => 'es',
                'translation_of' => '12',
                'parent_id' => '0',
                'name' => 'Human Resources',
                'slug' => 'human-resources',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '219',
                'rgt' => '220',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            42 => 
            array (
                'id' => '43',
                'translation_lang' => 'es',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Medical & Healthcare',
                'slug' => 'medical-healthcare',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '217',
                'rgt' => '218',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            43 => 
            array (
                'id' => '44',
                'translation_lang' => 'es',
                'translation_of' => '14',
                'parent_id' => '0',
                'name' => 'Tourism & Restaurants',
                'slug' => 'tourism-restaurants',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '211',
                'rgt' => '212',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            44 => 
            array (
                'id' => '45',
                'translation_lang' => 'es',
                'translation_of' => '15',
                'parent_id' => '0',
                'name' => 'Transportation & Logistics',
                'slug' => 'transportation-logistics',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '209',
                'rgt' => '210',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            45 => 
            array (
                'id' => '46',
                'translation_lang' => 'ar',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'هندسة',
                'slug' => 'engineering-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '203',
                'rgt' => '204',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            46 => 
            array (
                'id' => '47',
                'translation_lang' => 'ar',
                'translation_of' => '2',
                'parent_id' => '0',
                'name' => 'الخدمات المالية',
                'slug' => 'financial-services-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '197',
                'rgt' => '198',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            47 => 
            array (
                'id' => '48',
                'translation_lang' => 'ar',
                'translation_of' => '3',
                'parent_id' => '0',
                'name' => 'الخدمات المصرفية',
                'slug' => 'banking-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '195',
                'rgt' => '196',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            48 => 
            array (
                'id' => '49',
                'translation_lang' => 'ar',
                'translation_of' => '4',
                'parent_id' => '0',
                'name' => 'السلامة والأمن',
                'slug' => 'security-safety-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '193',
                'rgt' => '194',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            49 => 
            array (
                'id' => '50',
                'translation_lang' => 'ar',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'تدريب',
                'slug' => 'training-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '187',
                'rgt' => '188',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            50 => 
            array (
                'id' => '51',
                'translation_lang' => 'ar',
                'translation_of' => '6',
                'parent_id' => '0',
                'name' => 'خدمة عامة',
                'slug' => 'public-service-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '185',
                'rgt' => '186',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            51 => 
            array (
                'id' => '52',
                'translation_lang' => 'ar',
                'translation_of' => '7',
                'parent_id' => '0',
                'name' => 'العقارات',
                'slug' => 'real-estate-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '213',
                'rgt' => '214',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            52 => 
            array (
                'id' => '53',
                'translation_lang' => 'ar',
                'translation_of' => '8',
                'parent_id' => '0',
                'name' => 'مستقلة مستقلة',
                'slug' => 'independent-freelance-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '205',
                'rgt' => '206',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            53 => 
            array (
                'id' => '54',
                'translation_lang' => 'ar',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'تكنولوجيا المعلومات والاتصالات',
                'slug' => 'it-telecoms-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '207',
                'rgt' => '208',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            54 => 
            array (
                'id' => '55',
                'translation_lang' => 'ar',
                'translation_of' => '10',
                'parent_id' => '0',
                'name' => 'الاتصالات التسويقية',
                'slug' => 'marketing-communication-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '223',
                'rgt' => '224',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            55 => 
            array (
                'id' => '56',
                'translation_lang' => 'ar',
                'translation_of' => '11',
                'parent_id' => '0',
                'name' => 'خدمة مجالسة الأطفال و مربية',
                'slug' => 'babysitting-nanny-work-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '221',
                'rgt' => '222',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            56 => 
            array (
                'id' => '57',
                'translation_lang' => 'ar',
                'translation_of' => '12',
                'parent_id' => '0',
                'name' => 'الموارد البشرية',
                'slug' => 'human-resources-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '219',
                'rgt' => '220',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            57 => 
            array (
                'id' => '58',
                'translation_lang' => 'ar',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'الطبية والرعاية الصحية',
                'slug' => 'medical-healthcare-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '217',
                'rgt' => '218',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            58 => 
            array (
                'id' => '59',
                'translation_lang' => 'ar',
                'translation_of' => '14',
                'parent_id' => '0',
                'name' => 'السياحة والمطاعم',
                'slug' => 'tourism-restaurants-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '211',
                'rgt' => '212',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            59 => 
            array (
                'id' => '60',
                'translation_lang' => 'ar',
                'translation_of' => '15',
                'parent_id' => '0',
                'name' => 'النقل والخدمات اللوجستية',
                'slug' => 'transportation-logistics-ar',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '209',
                'rgt' => '210',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            60 => 
            array (
                'id' => '61',
                'translation_lang' => 'de',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Engineering',
                'slug' => 'engineering-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '203',
                'rgt' => '204',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            61 => 
            array (
                'id' => '62',
                'translation_lang' => 'de',
                'translation_of' => '2',
                'parent_id' => '0',
                'name' => 'Financial Services',
                'slug' => 'financial-services-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '197',
                'rgt' => '198',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            62 => 
            array (
                'id' => '63',
                'translation_lang' => 'de',
                'translation_of' => '3',
                'parent_id' => '0',
                'name' => 'Banking',
                'slug' => 'banking-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '195',
                'rgt' => '196',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            63 => 
            array (
                'id' => '64',
                'translation_lang' => 'de',
                'translation_of' => '4',
                'parent_id' => '0',
                'name' => 'Security & Safety',
                'slug' => 'security-safety-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '193',
                'rgt' => '194',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            64 => 
            array (
                'id' => '65',
                'translation_lang' => 'de',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'Training',
                'slug' => 'training-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '187',
                'rgt' => '188',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            65 => 
            array (
                'id' => '66',
                'translation_lang' => 'de',
                'translation_of' => '6',
                'parent_id' => '0',
                'name' => 'Public Service',
                'slug' => 'public-service-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '185',
                'rgt' => '186',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            66 => 
            array (
                'id' => '67',
                'translation_lang' => 'de',
                'translation_of' => '7',
                'parent_id' => '0',
                'name' => 'Real Estate',
                'slug' => 'real-estate-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '213',
                'rgt' => '214',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            67 => 
            array (
                'id' => '68',
                'translation_lang' => 'de',
                'translation_of' => '8',
                'parent_id' => '0',
                'name' => 'Independent & Freelance',
                'slug' => 'independent-freelance-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '205',
                'rgt' => '206',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            68 => 
            array (
                'id' => '69',
                'translation_lang' => 'de',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'IT & Telecoms',
                'slug' => 'it-telecoms-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '207',
                'rgt' => '208',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            69 => 
            array (
                'id' => '70',
                'translation_lang' => 'de',
                'translation_of' => '10',
                'parent_id' => '0',
                'name' => 'Marketing & Communication',
                'slug' => 'marketing-communication-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '223',
                'rgt' => '224',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            70 => 
            array (
                'id' => '71',
                'translation_lang' => 'de',
                'translation_of' => '11',
                'parent_id' => '0',
                'name' => 'Babysitting & Nanny Work',
                'slug' => 'babysitting-nanny-work-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '221',
                'rgt' => '222',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            71 => 
            array (
                'id' => '72',
                'translation_lang' => 'de',
                'translation_of' => '12',
                'parent_id' => '0',
                'name' => 'Human Resources',
                'slug' => 'human-resources-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '219',
                'rgt' => '220',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            72 => 
            array (
                'id' => '73',
                'translation_lang' => 'de',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Medical & Healthcare',
                'slug' => 'medical-healthcare-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '217',
                'rgt' => '218',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            73 => 
            array (
                'id' => '74',
                'translation_lang' => 'de',
                'translation_of' => '14',
                'parent_id' => '0',
                'name' => 'Tourism & Restaurants',
                'slug' => 'tourism-restaurants-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '211',
                'rgt' => '212',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
            74 => 
            array (
                'id' => '75',
                'translation_lang' => 'de',
                'translation_of' => '15',
                'parent_id' => '0',
                'name' => 'Transportation & Logistics',
                'slug' => 'transportation-logistics-de',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => '209',
                'rgt' => '210',
                'depth' => '2',
                'type' => 'classified',
                'active' => '1',
            ),
        ));
        
        
    }
}