<?php

use Illuminate\Database\Seeder;

class ModelCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('model_categories')->delete();
        
        \DB::table('model_categories')->insert(array (
            0 => 
            array (
                'id' => '1',
                'translation_lang' => 'en',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Baby Model',
                'slug' => 'baby-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            1 => 
            array (
                'id' => '2',
                'translation_lang' => 'fr',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Baby Model',
                'slug' => 'baby-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            2 => 
            array (
                'id' => '3',
                'translation_lang' => 'es',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Baby Model',
                'slug' => 'baby-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            3 => 
            array (
                'id' => '4',
                'translation_lang' => 'de',
                'translation_of' => '1',
                'parent_id' => '0',
                'name' => 'Baby Model',
                'slug' => 'baby-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            4 => 
            array (
                'id' => '5',
                'translation_lang' => 'en',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'Kids Model',
                'slug' => 'kids-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            5 => 
            array (
                'id' => '6',
                'translation_lang' => 'fr',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'Kids Model',
                'slug' => 'kids-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            6 => 
            array (
                'id' => '7',
                'translation_lang' => 'es',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'Kids Model',
                'slug' => 'kids-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            7 => 
            array (
                'id' => '8',
                'translation_lang' => 'de',
                'translation_of' => '5',
                'parent_id' => '0',
                'name' => 'Kindermodel',
                'slug' => 'kids-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            8 => 
            array (
                'id' => '9',
                'translation_lang' => 'en',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Model',
                'slug' => 'Model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            9 => 
            array (
                'id' => '10',
                'translation_lang' => 'fr',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Model',
                'slug' => 'Model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            10 => 
            array (
                'id' => '11',
                'translation_lang' => 'es',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Model',
                'slug' => 'Model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            11 => 
            array (
                'id' => '12',
                'translation_lang' => 'de',
                'translation_of' => '9',
                'parent_id' => '0',
                'name' => 'Model',
                'slug' => 'Model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            12 => 
            array (
                'id' => '13',
                'translation_lang' => 'en',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Best Ager Model',
                'slug' => 'bestager-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            13 => 
            array (
                'id' => '14',
                'translation_lang' => 'fr',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Best Ager Model',
                'slug' => 'bestager-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            14 => 
            array (
                'id' => '15',
                'translation_lang' => 'es',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => 'Best Ager Model',
                'slug' => 'bestager-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            15 => 
            array (
                'id' => '16',
                'translation_lang' => 'de',
                'translation_of' => '13',
                'parent_id' => '0',
                'name' => '50plus Model',
                'slug' => 'bestager-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            16 => 
            array (
                'id' => '17',
                'translation_lang' => 'en',
                'translation_of' => '17',
                'parent_id' => '0',
                'name' => 'Curvy Model',
                'slug' => 'curvy-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            17 => 
            array (
                'id' => '18',
                'translation_lang' => 'fr',
                'translation_of' => '17',
                'parent_id' => '0',
                'name' => 'Curvy Model',
                'slug' => 'curvy-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            18 => 
            array (
                'id' => '19',
                'translation_lang' => 'es',
                'translation_of' => '17',
                'parent_id' => '0',
                'name' => 'Curvy Model',
                'slug' => 'curvy-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            19 => 
            array (
                'id' => '20',
                'translation_lang' => 'de',
                'translation_of' => '17',
                'parent_id' => '0',
                'name' => 'Plus Size Model',
                'slug' => 'curvy-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            20 => 
            array (
                'id' => '21',
                'translation_lang' => 'en',
                'translation_of' => '21',
                'parent_id' => '0',
                'name' => 'Fitness Model',
                'slug' => 'fitness-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            21 => 
            array (
                'id' => '22',
                'translation_lang' => 'fr',
                'translation_of' => '21',
                'parent_id' => '0',
                'name' => 'Fitness Model',
                'slug' => 'fitness-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            22 => 
            array (
                'id' => '23',
                'translation_lang' => 'es',
                'translation_of' => '21',
                'parent_id' => '0',
                'name' => 'Fitness Model',
                'slug' => 'fitness-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
            23 => 
            array (
                'id' => '24',
                'translation_lang' => 'de',
                'translation_of' => '21',
                'parent_id' => '0',
                'name' => 'Fitness Model',
                'slug' => 'fitness-model',
                'description' => NULL,
                'picture' => NULL,
                'css_class' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'type' => 'classified',
                'active' => '1',
            ),
        ));
        
        
    }
}