<?php

use Illuminate\Database\Seeder;

class PackagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('packages')->delete();
        
        \DB::table('packages')->insert(array (
            0 => 
            array (
                'id' => '1',
                'translation_lang' => 'en',
                'translation_of' => '1',
                'name' => 'Partner Regular List AT',
                'short_name' => 'FREE',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '1',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '30',
                'description' => 'Display ads during 7 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'active' => '1',
            ),
            1 => 
            array (
                'id' => '2',
                'translation_lang' => 'en',
                'translation_of' => '2',
                'name' => 'Premium 30 days',
                'short_name' => 'Urgent',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '99.00',
                'currency_code' => 'USD',
                'tax' => '1.00',
                'duration' => '30',
                'description' => 'Display ads during 30 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'active' => '0',
            ),
            2 => 
            array (
                'id' => '3',
                'translation_lang' => 'en',
                'translation_of' => '3',
                'name' => 'Premium 90 days',
                'short_name' => 'Premium',
                'user_type_id' => NULL,
                'country_code' => NULL,
                'ribbon' => 'green',
                'has_badge' => '1',
                'price' => '129.00',
                'currency_code' => 'USD',
                'tax' => NULL,
                'duration' => '90',
                'description' => 'Display ads during 90 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'active' => '0',
            ),
            3 => 
            array (
                'id' => '4',
                'translation_lang' => 'fr',
                'translation_of' => '1',
                'name' => 'Gratuit',
                'short_name' => 'FREE',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '1',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '30',
                'description' => 'Annonce diffusée durant 7 jours',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'active' => '1',
            ),
            4 => 
            array (
                'id' => '5',
                'translation_lang' => 'fr',
                'translation_of' => '2',
                'name' => 'Premium 30 jours',
                'short_name' => 'Urgent',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '99.00',
                'currency_code' => 'USD',
                'tax' => '1.00',
                'duration' => '30',
                'description' => 'Annonce diffusée durant 30 jours',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '4',
                'rgt' => '7',
                'depth' => '1',
                'active' => '0',
            ),
            5 => 
            array (
                'id' => '6',
                'translation_lang' => 'fr',
                'translation_of' => '3',
                'name' => 'Premium 90 jours',
                'short_name' => 'Premium',
                'user_type_id' => NULL,
                'country_code' => NULL,
                'ribbon' => 'green',
                'has_badge' => '1',
                'price' => '129.00',
                'currency_code' => 'USD',
                'tax' => NULL,
                'duration' => '90',
                'description' => 'Annonce diffusée durant 90 jours',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'active' => '0',
            ),
            6 => 
            array (
                'id' => '7',
                'translation_lang' => 'es',
                'translation_of' => '1',
                'name' => 'Regular List',
                'short_name' => 'FREE',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '1',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '30',
                'description' => 'Display ads during 7 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'active' => '1',
            ),
            7 => 
            array (
                'id' => '8',
                'translation_lang' => 'es',
                'translation_of' => '2',
                'name' => 'Premium 30 days',
                'short_name' => 'Urgent',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '99.00',
                'currency_code' => 'USD',
                'tax' => '1.00',
                'duration' => '30',
                'description' => 'Display ads during 30 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '4',
                'rgt' => '7',
                'depth' => '1',
                'active' => '0',
            ),
            8 => 
            array (
                'id' => '9',
                'translation_lang' => 'es',
                'translation_of' => '3',
                'name' => 'Premium 90 days',
                'short_name' => 'Premium',
                'user_type_id' => NULL,
                'country_code' => NULL,
                'ribbon' => 'green',
                'has_badge' => '1',
                'price' => '129.00',
                'currency_code' => 'USD',
                'tax' => NULL,
                'duration' => '90',
                'description' => 'Display ads during 90 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'active' => '0',
            ),
            9 => 
            array (
                'id' => '10',
                'translation_lang' => 'ar',
                'translation_of' => '1',
                'name' => 'قائمة عادية',
                'short_name' => 'حر',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '1',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '30',
                'description' => 'عرض الإعلانات خلال 7 أيام',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'active' => '1',
            ),
            10 => 
            array (
                'id' => '11',
                'translation_lang' => 'ar',
                'translation_of' => '2',
                'name' => 'قسط 30 يوما',
                'short_name' => 'العاجلة',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '99.00',
                'currency_code' => 'USD',
                'tax' => '1.00',
                'duration' => '30',
                'description' => 'عرض الإعلانات خلال 30 يوما',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'active' => '0',
            ),
            11 => 
            array (
                'id' => '12',
                'translation_lang' => 'ar',
                'translation_of' => '3',
                'name' => 'قسط 90 يوما',
                'short_name' => 'علاوة',
                'user_type_id' => NULL,
                'country_code' => NULL,
                'ribbon' => 'green',
                'has_badge' => '0',
                'price' => '129.00',
                'currency_code' => 'USD',
                'tax' => NULL,
                'duration' => '90',
                'description' => 'عرض الإعلانات خلال 90 يوما',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'active' => '0',
            ),
            12 => 
            array (
                'id' => '13',
                'translation_lang' => 'de',
                'translation_of' => '1',
                'name' => 'Reguläre Auflistung',
                'short_name' => 'FREE',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '1',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '30',
                'description' => 'Display ads during 7 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'active' => '1',
            ),
            13 => 
            array (
                'id' => '14',
                'translation_lang' => 'de',
                'translation_of' => '2',
                'name' => 'Premium 30 days',
                'short_name' => 'Urgent',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '99.00',
                'currency_code' => 'USD',
                'tax' => '1.00',
                'duration' => '30',
                'description' => 'Display ads during 30 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'active' => '0',
            ),
            14 => 
            array (
                'id' => '15',
                'translation_lang' => 'de',
                'translation_of' => '3',
                'name' => 'Premium 90 days',
                'short_name' => 'Premium',
                'user_type_id' => NULL,
                'country_code' => 'AT',
                'ribbon' => 'green',
                'has_badge' => '1',
                'price' => '129.00',
                'currency_code' => 'USD',
                'tax' => NULL,
                'duration' => '90',
                'description' => 'Display ads during 90 days',
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => '0',
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'active' => '0',
            ),
            15 => 
            array (
                'id' => '16',
                'translation_lang' => 'en',
                'translation_of' => '16',
                'name' => 'Models Premium Membership AT',
                'short_name' => 'Premium',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => 'green',
                'has_badge' => '1',
                'price' => '132.00',
                'currency_code' => 'EUR',
                'tax' => '1.00',
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p><ul><li><br></li></ul>',
                'parent_id' => NULL,
                'lft' => '1',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            16 => 
            array (
                'id' => '17',
                'translation_lang' => 'fr',
                'translation_of' => '16',
                'name' => 'Models Premium Membership',
                'short_name' => 'Premium',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => 'green',
                'has_badge' => '1',
                'price' => '132.00',
                'currency_code' => 'EUR',
                'tax' => '1.00',
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p><ul><li><br></li></ul>',
                'parent_id' => NULL,
                'lft' => '1',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            17 => 
            array (
                'id' => '18',
                'translation_lang' => 'es',
                'translation_of' => '16',
                'name' => 'Models Premium Membership',
                'short_name' => 'Premium',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => 'green',
                'has_badge' => '1',
                'price' => '132.00',
                'currency_code' => 'EUR',
                'tax' => '1.00',
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p><ul><li><br></li></ul>',
                'parent_id' => NULL,
                'lft' => '1',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            18 => 
            array (
                'id' => '19',
                'translation_lang' => 'de',
                'translation_of' => '16',
                'name' => 'Models Premium Membership AT',
                'short_name' => 'Premium',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => 'green',
                'has_badge' => '1',
                'price' => '132.00',
                'currency_code' => 'EUR',
                'tax' => '1.00',
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p><ul><li><br></li></ul>',
                'parent_id' => NULL,
                'lft' => '1',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            19 => 
            array (
                'id' => '20',
                'translation_lang' => 'en',
                'translation_of' => '20',
                'name' => 'Models Premium Membership DE',
                'short_name' => 'Premium DE',
                'user_type_id' => '3',
                'country_code' => 'DE',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            20 => 
            array (
                'id' => '21',
                'translation_lang' => 'fr',
                'translation_of' => '20',
                'name' => 'Models Premium Membership DE',
                'short_name' => 'Premium DE',
                'user_type_id' => '3',
                'country_code' => 'DE',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            21 => 
            array (
                'id' => '22',
                'translation_lang' => 'es',
                'translation_of' => '20',
                'name' => 'Models Premium Membership DE',
                'short_name' => 'Premium DE',
                'user_type_id' => '3',
                'country_code' => 'DE',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            22 => 
            array (
                'id' => '23',
                'translation_lang' => 'de',
                'translation_of' => '20',
                'name' => 'Models Premium Membership DE',
                'short_name' => 'Premium DE',
                'user_type_id' => '3',
                'country_code' => 'DE',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            23 => 
            array (
                'id' => '24',
                'translation_lang' => 'en',
                'translation_of' => '24',
                'name' => 'Models Premium Membership CH',
                'short_name' => 'Premium CH',
                'user_type_id' => '3',
                'country_code' => 'CH',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'CHF',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            24 => 
            array (
                'id' => '25',
                'translation_lang' => 'fr',
                'translation_of' => '24',
                'name' => 'Models Premium Membership CH',
                'short_name' => 'Premium CH',
                'user_type_id' => '3',
                'country_code' => 'CH',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'CHF',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            25 => 
            array (
                'id' => '26',
                'translation_lang' => 'es',
                'translation_of' => '24',
                'name' => 'Models Premium Membership CH',
                'short_name' => 'Premium CH',
                'user_type_id' => '3',
                'country_code' => 'CH',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'CHF',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            26 => 
            array (
                'id' => '27',
                'translation_lang' => 'de',
                'translation_of' => '24',
                'name' => 'Models Premium Membership CH',
                'short_name' => 'Premium CH',
                'user_type_id' => '3',
                'country_code' => 'CH',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'CHF',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            27 => 
            array (
                'id' => '28',
                'translation_lang' => 'en',
                'translation_of' => '28',
                'name' => 'Models Premium Membership LI',
                'short_name' => 'Premium LI',
                'user_type_id' => '3',
                'country_code' => 'LI',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'CHF',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            28 => 
            array (
                'id' => '29',
                'translation_lang' => 'fr',
                'translation_of' => '28',
                'name' => 'Models Premium Membership LI',
                'short_name' => 'Premium LI',
                'user_type_id' => '3',
                'country_code' => 'LI',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'CHF',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            29 => 
            array (
                'id' => '30',
                'translation_lang' => 'es',
                'translation_of' => '28',
                'name' => 'Models Premium Membership LI',
                'short_name' => 'Premium LI',
                'user_type_id' => '3',
                'country_code' => 'LI',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'CHF',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            30 => 
            array (
                'id' => '31',
                'translation_lang' => 'de',
                'translation_of' => '28',
                'name' => 'Models Premium Membership LI',
                'short_name' => 'Premium LI',
                'user_type_id' => '3',
                'country_code' => 'LI',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '132.00',
                'currency_code' => 'CHF',
                'tax' => NULL,
                'duration' => '365',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            31 => 
            array (
                'id' => '32',
                'translation_lang' => 'en',
                'translation_of' => '32',
                'name' => 'Models Premium Membership AT',
                'short_name' => 'Models Premium Membership AT',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '199.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '730',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => '2',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '0',
            ),
            32 => 
            array (
                'id' => '33',
                'translation_lang' => 'fr',
                'translation_of' => '32',
                'name' => 'Models Premium Membership AT',
                'short_name' => 'Models Premium Membership AT',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '199.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '730',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => '2',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '0',
            ),
            33 => 
            array (
                'id' => '34',
                'translation_lang' => 'es',
                'translation_of' => '32',
                'name' => 'Models Premium Membership AT',
                'short_name' => 'Models Premium Membership AT',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '199.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '730',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => '2',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '0',
            ),
            34 => 
            array (
                'id' => '35',
                'translation_lang' => 'de',
                'translation_of' => '32',
                'name' => 'Models Premium Membership AT',
                'short_name' => 'Models Premium Membership AT',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '199.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '730',
                'description' => NULL,
            'features' => '<p>Sichtbar für Partner</p><p>Erhalte Job-Anfragen</p><p>Werde von Partnern gebucht</p><p>Kontakt durch Partner möglich</p><p>Partner Liste</p><p>Partner Details</p><p>Partner Geo-Suche</p><p>Eigenes Model Portfolio</p><p>Werde von Partnern als Favorit markiert</p><p>Erstelle Job Alarme</p><p>Bewirb dich bei Jobs</p><p>Erweiterte Partnersuche</p><p>Time for Prints (TFP) Details</p><p>Online PDF Sedcard</p><p>150 MB Speicher für Photos (max. 30 a 5MB)</p>',
                'parent_id' => NULL,
                'lft' => '2',
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '0',
            ),
            35 => 
            array (
                'id' => '36',
                'translation_lang' => 'en',
                'translation_of' => '36',
                'name' => 'Models Premium Membership AT FREE',
                'short_name' => 'Models Premium Membership AT FREE',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => NULL,
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            36 => 
            array (
                'id' => '37',
                'translation_lang' => 'fr',
                'translation_of' => '36',
                'name' => 'Models Premium Membership AT FREE',
                'short_name' => 'Models Premium Membership AT FREE',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => NULL,
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            37 => 
            array (
                'id' => '38',
                'translation_lang' => 'es',
                'translation_of' => '36',
                'name' => 'Models Premium Membership AT FREE',
                'short_name' => 'Models Premium Membership AT FREE',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => NULL,
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            38 => 
            array (
                'id' => '39',
                'translation_lang' => 'de',
                'translation_of' => '36',
                'name' => 'Models Premium Membership AT FREE',
                'short_name' => 'Models Premium Membership AT FREE',
                'user_type_id' => '3',
                'country_code' => 'AT',
                'ribbon' => NULL,
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => NULL,
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            39 => 
            array (
                'id' => '40',
                'translation_lang' => 'de',
                'translation_of' => '41',
                'name' => 'Model Booker dazubuchen',
                'short_name' => 'Model booker',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '25.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '30',
                'description' => NULL,
                'features' => '<p>- Wir helfen dir bei der Suche nach pasenden Models&nbsp;</p><p>- Dein Model Booker sucht Models und kontaktiert Sie für Dich&nbsp;</p><p>- Wir stellen dir den Kontakt zu dem Model direkt her&nbsp;</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            40 => 
            array (
                'id' => '41',
                'translation_lang' => 'en',
                'translation_of' => '41',
                'name' => 'Model Booker dazubuchen',
                'short_name' => 'Model booker',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '25.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '30',
                'description' => NULL,
                'features' => '<p>- Wir helfen dir bei der Suche nach pasenden Models&nbsp;</p><p>- Dein Model Booker sucht Models und kontaktiert Sie für Dich&nbsp;</p><p>- Wir stellen dir den Kontakt zu dem Model direkt her&nbsp;</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            41 => 
            array (
                'id' => '42',
                'translation_lang' => 'fr',
                'translation_of' => '41',
                'name' => 'Model Booker dazubuchen',
                'short_name' => 'Model booker',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '25.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '30',
                'description' => NULL,
                'features' => '<p>- Wir helfen dir bei der Suche nach pasenden Models&nbsp;</p><p>- Dein Model Booker sucht Models und kontaktiert Sie für Dich&nbsp;</p><p>- Wir stellen dir den Kontakt zu dem Model direkt her&nbsp;</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            42 => 
            array (
                'id' => '43',
                'translation_lang' => 'es',
                'translation_of' => '41',
                'name' => 'Model Booker dazubuchen',
                'short_name' => 'Model booker',
                'user_type_id' => '2',
                'country_code' => 'AT',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '25.00',
                'currency_code' => 'EUR',
                'tax' => NULL,
                'duration' => '30',
                'description' => NULL,
                'features' => '<p>- Wir helfen dir bei der Suche nach pasenden Models&nbsp;</p><p>- Dein Model Booker sucht Models und kontaktiert Sie für Dich&nbsp;</p><p>- Wir stellen dir den Kontakt zu dem Model direkt her&nbsp;</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            43 => 
            array (
                'id' => '44',
                'translation_lang' => 'de',
                'translation_of' => '45',
                'name' => 'Reguläre Auflistung DE',
                'short_name' => 'FREE',
                'user_type_id' => '2',
                'country_code' => 'DE',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            44 => 
            array (
                'id' => '45',
                'translation_lang' => 'en',
                'translation_of' => '45',
                'name' => 'Reguläre Auflistung DE',
                'short_name' => 'FREE',
                'user_type_id' => '2',
                'country_code' => 'DE',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            45 => 
            array (
                'id' => '46',
                'translation_lang' => 'fr',
                'translation_of' => '45',
                'name' => 'Reguläre Auflistung DE',
                'short_name' => 'FREE',
                'user_type_id' => '2',
                'country_code' => 'DE',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            46 => 
            array (
                'id' => '47',
                'translation_lang' => 'es',
                'translation_of' => '45',
                'name' => 'Reguläre Auflistung DE',
                'short_name' => 'FREE',
                'user_type_id' => '2',
                'country_code' => 'DE',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'EUR',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            47 => 
            array (
                'id' => '48',
                'translation_lang' => 'de',
                'translation_of' => '49',
                'name' => 'Reguläre Auflistung CH',
                'short_name' => 'FREE ch',
                'user_type_id' => '2',
                'country_code' => 'CH',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'CHF',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            48 => 
            array (
                'id' => '49',
                'translation_lang' => 'en',
                'translation_of' => '49',
                'name' => 'Reguläre Auflistung CH',
                'short_name' => 'FREE ch',
                'user_type_id' => '2',
                'country_code' => 'CH',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'CHF',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            49 => 
            array (
                'id' => '50',
                'translation_lang' => 'fr',
                'translation_of' => '49',
                'name' => 'Reguläre Auflistung CH',
                'short_name' => 'FREE ch',
                'user_type_id' => '2',
                'country_code' => 'CH',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'CHF',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            50 => 
            array (
                'id' => '51',
                'translation_lang' => 'es',
                'translation_of' => '49',
                'name' => 'Reguläre Auflistung CH',
                'short_name' => 'FREE ch',
                'user_type_id' => '2',
                'country_code' => 'CH',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'CHF',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            51 => 
            array (
                'id' => '52',
                'translation_lang' => 'de',
                'translation_of' => '53',
                'name' => 'Reguläre Auflistung LI',
                'short_name' => 'free li',
                'user_type_id' => '2',
                'country_code' => 'LI',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'CHF',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            52 => 
            array (
                'id' => '53',
                'translation_lang' => 'en',
                'translation_of' => '53',
                'name' => 'Reguläre Auflistung LI',
                'short_name' => 'free li',
                'user_type_id' => '2',
                'country_code' => 'LI',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'CHF',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            53 => 
            array (
                'id' => '54',
                'translation_lang' => 'fr',
                'translation_of' => '53',
                'name' => 'Reguläre Auflistung LI',
                'short_name' => 'free li',
                'user_type_id' => '2',
                'country_code' => 'LI',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'CHF',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
            54 => 
            array (
                'id' => '55',
                'translation_lang' => 'es',
                'translation_of' => '53',
                'name' => 'Reguläre Auflistung LI',
                'short_name' => 'free li',
                'user_type_id' => '2',
                'country_code' => 'LI',
                'ribbon' => 'red',
                'has_badge' => '0',
                'price' => '0.00',
                'currency_code' => 'CHF',
                'tax' => '0.00',
                'duration' => '365',
                'description' => NULL,
                'features' => '<p>- Job kostenlos einstellen&nbsp;</p><p>- Models können sich direkt auf Deinen Job bewerben</p><p>- Finde passende Models und buche Models direkt</p><p>- Keine Vermittlungsprovision</p>',
                'parent_id' => NULL,
                'lft' => NULL,
                'rgt' => NULL,
                'depth' => NULL,
                'active' => '1',
            ),
        ));
        
        
    }
}