<?php

use Illuminate\Database\Seeder;

class PagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pages')->delete();
        
        \DB::table('pages')->insert(array (
            0 => 
            array (
                'id' => '1',
                'translation_lang' => 'en',
                'translation_of' => '1',
                'parent_id' => '0',
                'type' => 'terms',
                'name' => 'Terms',
                'slug' => 'terms',
                'title' => 'Terms & Conditions',
                'picture' => NULL,
            'content' => '<h4><b>Definitions</b></h4><p>Each of the terms mentioned below have in these Conditions of Sale JobClass Service (hereinafter the "Conditions") the following meanings:</p><ol><li>Announcement&nbsp;: refers to all the elements and data (visual, textual, sound, photographs, drawings), presented by an Advertiser editorial under his sole responsibility, in order to buy, rent or sell a product or service and broadcast on the Website and Mobile Site.</li><li>Advertiser&nbsp;: means any natural or legal person, a major, established in France, holds an account and having submitted an announcement, from it, on the Website. Any Advertiser must be connected to the Personal Account for deposit and or manage its ads. Ad first deposit automatically entails the establishment of a Personal Account to the Advertiser.</li><li>Personal Account&nbsp;: refers to the free space than any Advertiser must create and which it should connect from the Website to disseminate, manage and view its ads.</li><li>JobClass&nbsp;: means the company that publishes and operates the Website and Mobile Site {YourCompany}, registered at the Trade and Companies Register of Cotonou under the number {YourCompany Registration Number} whose registered office is at {YourCompany Address}.</li><li>Customer Service&nbsp;: JobClass means the department to which the Advertiser may obtain further information. This service can be contacted via email by clicking the link on the Website and Mobile Site.</li><li>JobClass Service&nbsp;: JobClass means the services made available to Users and Advertisers on the Website and Mobile Site.</li><li>Website&nbsp;: means the website operated by JobClass accessed mainly from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access the Service via internet JobClass.</li><li>Mobile Site&nbsp;: is the mobile site operated by JobClass accessible from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access via their mobile phone service {YourSiteName}.</li><li>User&nbsp;: any visitor with access to JobClass Service via the Website and Mobile Site and Consultant Service JobClass accessible from different media.</li></ol><h4><b>Subject</b></h4><p>These Terms and Conditions Of Use establish the contractual conditions applicable to any subscription by an Advertiser connected to its Personal Account from the Website and Mobile Site.<br></p><h4><b>Acceptance</b></h4><p>Any use of the website by an Advertiser is full acceptance of the current Terms.<br></p><h4><b>Responsibility</b></h4><p>Responsibility for JobClass can not be held liable for non-performance or improper performance of due control, either because of the Advertiser, or a case of major force.<br></p><h4><b>Modification of these terms</b></h4><p>JobClass reserves the right, at any time, to modify all or part of the Terms and Conditions.</p><p>Advertisers are advised to consult the Terms to be aware of the changes.</p><h4><b>Miscellaneous</b></h4><p>If part of the Terms should be illegal, invalid or unenforceable for any reason whatsoever, the provisions in question would be deemed unwritten, without questioning the validity of the remaining provisions will continue to apply between Advertisers and JobClass.</p><p>Any complaints should be addressed to Customer Service JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:10:40',
                'updated_at' => '2017-02-13 18:22:30',
            ),
            1 => 
            array (
                'id' => '2',
                'translation_lang' => 'fr',
                'translation_of' => '1',
                'parent_id' => '0',
                'type' => 'terms',
                'name' => 'CGU',
                'slug' => 'cgu',
                'title' => 'Conditions d\'utilisation et de vente',
                'picture' => NULL,
            'content' => '<p><b>Définitions</b><br></p><p>Chacun des termes mentionnés ci-dessous aura dans les présentes Conditions Générales d\'Utilisation et de Vente du Service JobClass (ci-après dénommées les « CGU/CGV ») la signification suivante :</p><ol><li>Annonce : désigne l\'ensemble des éléments et données (visuelles, textuelles, sonores, photographies, dessins), déposé par un Annonceur sous sa responsabilité éditoriale exclusive, en vue d\'acheter, de louer ou de vendre un bien ou un service et diffusé sur le Site Internet et le Site Mobile.</li><li>Annonceur : désigne toute personne physique ou morale, majeure, établie en États-Unis, titulaire d\'un Compte et ayant déposé une Annonce, à partir de celui-ci, sur le Site Internet. Tout Annonceur doit impérativement être connecté à son Compte Personnel pour déposer et gérer sa ou ses Annonces. Tout premier dépôt d’annonce entraîne automatiquement la création d’un Compte Personnel propre à l’Annonceur.</li><li>Compte Personnel : désigne l\'espace gratuit que tout Annonceur doit se créer et auquel il doit se connecter depuis le Site Internet, afin de diffuser, gérer et visualiser ses annonces.</li><li>JobClass : désigne la société qui édite et exploite le Site Internet et le Site Mobile {YourCompany}, immatriculée au registre du commerce et des sociétés de Cotonou sous le numéro {YourCompany Registration Number} dont le siège social est situé {YourCompany Address}.</li><li>Service client : désigne le service de JobClass auprès duquel l\'Annonceur peut obtenir toute information complémentaire. Ce service peut être contacté par e-mail en cliquant sur le lien présent sur le Site Internet et le Site Mobile.</li><li>Service JobClass : désigne les services JobClass mis à la disposition des Utilisateurs et des Annonceurs sur le Site Internet et le Site Mobile.</li><li>Site Internet : désigne le site internet exploité par JobClass accessible principalement depuis l\'URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> et permettant aux Utilisateurs et aux Annonceurs d\'accéder via internet au Service JobClass.</li><li>Site Mobile : désigne le site mobile exploité par JobClass accessible depuis l\'URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> et permettant aux Utilisateurs et aux Annonceurs d\'accéder via leur téléphone mobile au Service JobClass.</li><li>Utilisateur : désigne tout visiteur, ayant accès au Service JobClass via le Site Internet et le Site Mobile et consultant le Service JobClass accessible depuis les différents supports.</li></ol><p><b>Objet</b></p><p>Les présentes Conditions Générales d\'Utilisation et de Vente (CGU/GCV) établissent les conditions contractuelles applicables à toute souscription, par un Annonceur connecté à son Compte Personnel depuis le Site Internet et le Site Mobile.</p><p><b>Acceptation</b></p><p>Toute utilisation du site du Site par un Annonceur vaut acceptation pleine et entière des CGU/CGV en vigueur.</p><p><b>Responsabilité</b></p><p>La responsabilité de JobClass ne peut être engagée en cas d\'inexécution ou de mauvaise exécution de la commande due, soit du fait de l\'Annonceur, soit d\'un cas de force majeure.</p><p><b>Modification des Conditions</b></p><p>JobClass se réserve la possibilité, à tout moment, de modifier en tout ou partie les CGV.<br>Les Annonceurs sont invités à consulter régulièrement les CGV afin de prendre connaissance des changements apportés.</p><p><b>Dispositions Diverses</b></p><p>Si une partie des CGV devait s\'avérer illégale, invalide ou inapplicable, pour quelque raison que ce soit, les dispositions en question seraient réputées non écrites, sans remettre en cause la validité des autres dispositions qui continueront de s\'appliquer entre les Annonceurs et JobClass.</p><p>Toute réclamation doit être adressée au Service Client de JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:10:40',
                'updated_at' => '2017-02-13 18:22:30',
            ),
            2 => 
            array (
                'id' => '3',
                'translation_lang' => 'es',
                'translation_of' => '1',
                'parent_id' => '0',
                'type' => 'terms',
                'name' => 'Términos',
                'slug' => 'terminos',
                'title' => 'Términos y Condiciones',
                'picture' => NULL,
            'content' => '<h4 style="margin-left: 0px;"><b>Definitions</b></h4><p>Each of the terms mentioned below have in these Conditions of Sale JobClass Service (hereinafter the "Conditions") the following meanings:</p><ol><li>Announcement&nbsp;: refers to all the elements and data (visual, textual, sound, photographs, drawings), presented by an Advertiser editorial under his sole responsibility, in order to buy, rent or sell a product or service and broadcast on the Website and Mobile Site.</li><li>Advertiser&nbsp;: means any natural or legal person, a major, established in France, holds an account and having submitted an announcement, from it, on the Website. Any Advertiser must be connected to the Personal Account for deposit and or manage its ads. Ad first deposit automatically entails the establishment of a Personal Account to the Advertiser.</li><li>Personal Account&nbsp;: refers to the free space than any Advertiser must create and which it should connect from the Website to disseminate, manage and view its ads.</li><li>JobClass&nbsp;: means the company that publishes and operates the Website and Mobile Site {YourCompany}, registered at the Trade and Companies Register of Cotonou under the number {YourCompany Registration Number} whose registered office is at {YourCompany Address}.</li><li>Customer Service&nbsp;: JobClass means the department to which the Advertiser may obtain further information. This service can be contacted via email by clicking the link on the Website and Mobile Site.</li><li>JobClass Service&nbsp;: JobClass means the services made available to Users and Advertisers on the Website and Mobile Site.</li><li>Website&nbsp;: means the website operated by JobClass accessed mainly from the URL&nbsp;<a href="http://www.bedigit.com/">http://www.bedigit.com</a>&nbsp;and allowing Users and Advertisers to access the Service via internet JobClass.</li><li>Mobile Site&nbsp;: is the mobile site operated by JobClass accessible from the URL&nbsp;<a href="http://www.bedigit.com/">http://www.bedigit.com</a>&nbsp;and allowing Users and Advertisers to access via their mobile phone service JobClass.</li><li>User&nbsp;: any visitor with access to JobClass Service via the Website and Mobile Site and Consultant Service JobClass accessible from different media.</li></ol><h4><b>Subject</b></h4><p>These Terms and Conditions Of Use establish the contractual conditions applicable to any subscription by an Advertiser connected to its Personal Account from the Website and Mobile Site.<br></p><h4><b>Acceptance</b></h4><p>Any use of the website by an Advertiser is full acceptance of the current Terms.<br></p><h4><b>Responsibility</b></h4><p>Responsibility for JobClass can not be held liable for non-performance or improper performance of due control, either because of the Advertiser, or a case of force majeure.<br></p><h4><b>Modification of these terms</b></h4><p>JobClass reserves the right, at any time, to modify all or part of the Terms and Conditions.</p><p>Advertisers are advised to consult the Terms to be aware of the changes.</p><h4><b>Miscellaneous</b></h4><p>If part of the Terms should be illegal, invalid or unenforceable for any reason whatsoever, the provisions in question would be deemed unwritten, without questioning the validity of the remaining provisions will continue to apply between Advertisers and JobClass.</p><p>Any complaints should be addressed to Customer Service JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:10:40',
                'updated_at' => '2017-02-13 18:22:30',
            ),
            3 => 
            array (
                'id' => '4',
                'translation_lang' => 'en',
                'translation_of' => '4',
                'parent_id' => '0',
                'type' => 'privacy',
                'name' => 'Privacy',
                'slug' => 'privacy',
                'title' => 'Privacy',
                'picture' => NULL,
            'content' => '<p>Your privacy is an important part of our relationship with you. Protecting your privacy is only part of our mission to provide a secure web environment. When using our site, including our services, your information will remain strictly confidential. Contributions made on our blog or on our forum are open to public view; so please do not post any personal information in your dealings with others. We accept no liability for those actions because it is your sole responsibility to adequate and safe post content on our site. We will not share, rent or share your information with third parties.</p><p>When you visit our site, we collect technical information about your computer and how you access our website and analyze this information such as Internet Protocol (IP) address of your computer, the operating system used by your computer, the browser (eg, Chrome, Firefox, Internet Explorer or other) your computer uses, the name of your Internet service provider (ISP), the Uniform Resource Locator (URL) of the website from which you come and the URL to which you go next and certain operating metrics such as the number of times you use our website. This general information can be used to help us better understand how our site is viewed and used. We may share this general information about our site with our business partners or the general public. For example, we may share the information on the number of daily unique visitors to our site with potential corporate partners or use them for advertising purposes. This information does contain any of your personal data that can be used to contact you or identify you.</p><p>When we place links or banners to other sites of our website, please note that we do not control this kind of content or practices or privacy policies of those sites. We do not endorse or assume no responsibility for the privacy policies or information collection practices of any other website other than managed sites JobClass.</p><p>We use the highest security standard available to protect your identifiable information in transit to us. All data stored on our servers are protected by a secure firewall for the unauthorized use or activity can not take place. Although we make every effort to protect your personal information against loss, misuse or alteration by third parties, you should be aware that there is always a risk that low-intentioned manage to find a way to thwart our security system or that Internet transmissions could be intercepted.</p><p>We reserve the right, without notice, to change, modify, add or remove portions of our Privacy Policy at any time and from time to time. These changes will be posted publicly on our website. When you visit our website, you accept all the terms of our privacy policy. Your continued use of this website constitutes your continued agreement to these terms. If you do not agree with the terms of our privacy policy, you should cease using our website.</p>',
                'external_link' => NULL,
                'lft' => '8',
                'rgt' => '9',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:28:37',
                'updated_at' => '2017-02-12 23:24:52',
            ),
            4 => 
            array (
                'id' => '5',
                'translation_lang' => 'fr',
                'translation_of' => '4',
                'parent_id' => '0',
                'type' => 'privacy',
                'name' => 'Vie privée',
                'slug' => 'vie-privee',
                'title' => 'Vie privée',
                'picture' => NULL,
            'content' => '<p>Votre vie privée est une partie importante de notre relation avec vous. Protéger votre vie privée n’est qu’une partie de notre mission de vous fournir un environnement Web sécurisé. Lorsque vous utilisez notre site y compris nos prestations, vos informations resteront strictement confidentielles. Les contributions faites sur notre blog ou sur notre forum sont ouverts à l’affichage public; ainsi nous vous invitons à ne pas poster d’informations personnelles dans vos échanges avec d’autres utilisateurs. Nous déclinons toute responsabilité de ces actions car il est de votre seule responsabilité de poster des contenus appropriés et sûrs sur notre site. Nous n’allons pas partager, louer ou échanger vos informations avec des tiers.</p><p>Lorsque vous visitez notre site, nous collectons des informations techniques relatives à votre ordinateur et la manière dont vous accédez à notre site internet et analysons ces informations telles que l’adresse de Protocole Internet (IP) de votre ordinateur, le système d’exploitation utilisé par votre ordinateur, le navigateur (par exemple, Chrome, Firefox, Internet Explorer ou autre) que votre ordinateur utilise, le nom de votre fournisseur de services Internet (FAI), le Uniform Resource Locator (URL) du site Web à partir duquel vous venez et l’URL vers laquelle vous allez prochaine et certaines mesures d’exploitation tels que le nombre de fois que vous utilisez notre site Web. Ces informations générales peuvent être utilisées pour nous aider à mieux comprendre comment notre site est vu et utilisé. Nous pouvons partager ces informations générales sur notre site avec nos partenaires d’affaires ou le grand public. Par exemple, nous pouvons partager les informations sur le nombre de visiteurs uniques quotidien sur notre site avec des entreprises partenaires potentiels ou les utiliser à des fins publicitaires. Ces informations ne contiennent aucune de vos données personnelles qui peuvent être utilisées pour vous contacter ou vous identifier.</p><p>Quand nous plaçons des liens ou des bannières publicitaires vers d’autres sites de notre site Web, veuillez noter que nous ne contrôlons pas ce genre de contenu, ni les pratiques ou les politiques de vie privée de ces sites. Nous ne soutenons ni n’assumons responsable des politiques de confidentialité ou les pratiques de collecte de renseignements de tout autre site internet autre que les sites gérés par JobClass.</p><p>Nous utilisons la norme de sécurité la plus élevée disponible pour protéger vos informations identifiables qui transitent vers nous. Toutes les données stockées sur nos serveurs sont protégés par un pare-feu sécurisé pour que l’utilisation ou activité non autorisée ne puisse pas avoir lieu. Bien que nous ferons tous les efforts pour protéger vos renseignements personnels contre la perte, l’usage abusif ou la modification par des tiers, vous devez être conscient qu’il y a toujours un certain risque que des personnes peu intentionnées arrivent à trouver un moyen de contrecarrer notre système de sécurité ou que les transmissions sur Internet soient interceptées.</p><p>Nous nous réservons le droit, sans préavis, de changer, modifier, ajouter ou retirer des parties de notre politique de confidentialité à tout moment et de temps à autre. Ces changements seront affichés publiquement sur notre site. Lorsque vous visitez notre site, vous acceptez tous les termes de notre politique de confidentialité. Votre utilisation continue de notre site constitue la continuité de votre accord à ces termes. Si vous n’êtes pas d’accord avec les termes de notre politique de confidentialité, vous devez cesser d’utiliser notre site Web.</p>',
                'external_link' => NULL,
                'lft' => '8',
                'rgt' => '9',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:28:37',
                'updated_at' => '2017-02-12 23:24:52',
            ),
            5 => 
            array (
                'id' => '6',
                'translation_lang' => 'es',
                'translation_of' => '4',
                'parent_id' => '0',
                'type' => 'privacy',
                'name' => 'Vida privada',
                'slug' => 'vida-privada',
                'title' => 'Vida privada',
                'picture' => NULL,
            'content' => '<p>Your privacy is an important part of our relationship with you. Protecting your privacy is only part of our mission to provide a secure web environment. When using our site, including our services, your information will remain strictly confidential. Contributions made on our blog or on our forum are open to public view; so please do not post any personal information in your dealings with others. We accept no liability for those actions because it is your sole responsibility to adequate and safe post content on our site. We will not share, rent or share your information with third parties.</p><p>When you visit our site, we collect technical information about your computer and how you access our website and analyze this information such as Internet Protocol (IP) address of your computer, the operating system used by your computer, the browser (eg, Chrome, Firefox, Internet Explorer or other) your computer uses, the name of your Internet service provider (ISP), the Uniform Resource Locator (URL) of the website from which you come and the URL to which you go next and certain operating metrics such as the number of times you use our website. This general information can be used to help us better understand how our site is viewed and used. We may share this general information about our site with our business partners or the general public. For example, we may share the information on the number of daily unique visitors to our site with potential corporate partners or use them for advertising purposes. This information does contain any of your personal data that can be used to contact you or identify you.</p><p>When we place links or banners to other sites of our website, please note that we do not control this kind of content or practices or privacy policies of those sites. We do not endorse or assume no responsibility for the privacy policies or information collection practices of any other website other than managed sites JobClass.</p><p>We use the highest security standard available to protect your identifiable information in transit to us. All data stored on our servers are protected by a secure firewall for the unauthorized use or activity can not take place. Although we make every effort to protect your personal information against loss, misuse or alteration by third parties, you should be aware that there is always a risk that low-intentioned manage to find a way to thwart our security system or that Internet transmissions could be intercepted.</p><p>We reserve the right, without notice, to change, modify, add or remove portions of our Privacy Policy at any time and from time to time. These changes will be posted publicly on our website. When you visit our website, you accept all the terms of our privacy policy. Your continued use of this website constitutes your continued agreement to these terms. If you do not agree with the terms of our privacy policy, you should cease using our website.</p>',
                'external_link' => NULL,
                'lft' => '8',
                'rgt' => '9',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:28:37',
                'updated_at' => '2017-02-12 23:24:52',
            ),
            6 => 
            array (
                'id' => '7',
                'translation_lang' => 'en',
                'translation_of' => '7',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'Anti-Scam',
                'slug' => 'anti-scam',
                'title' => 'Anti-Scam',
                'picture' => NULL,
            'content' => '<p><b>Protect yourself against Internet fraud!</b></p><p>The vast majority of ads are posted by honest people and trust. So you can do excellent business. Despite this, it is important to follow a few common sense rules following to prevent any attempt to scam.</p><p><b>Our advices</b></p><ul><li>Doing business with people you can meet in person.</li><li>Never send money by Western Union, MoneyGram or other anonymous payment systems.</li><li>Never send money or products abroad.</li><li>Do not accept checks.</li><li>Ask about the person you\'re dealing with another confirming source name, address and telephone number.</li><li>Keep copies of all correspondence (emails, ads, letters, etc.) and details of the person.</li><li>If a deal seems too good to be true, there is every chance that this is the case. Refrain.</li></ul><p><b>Recognize attempted scam</b></p><ul><li>The majority of scams have one or more of these characteristics:</li><li>The person is abroad or traveling abroad.</li><li>The person refuses to meet you in person.</li><li>Payment is made through Western Union, Money Gram or check.</li><li>The messages are in broken language (English or French or ...).</li><li>The texts seem to be copied and pasted.</li><li>The deal seems to be too good to be true.</li></ul>',
                'external_link' => NULL,
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:31:56',
                'updated_at' => '2017-02-12 23:24:52',
            ),
            7 => 
            array (
                'id' => '8',
                'translation_lang' => 'fr',
                'translation_of' => '7',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'Anti-Arnaque',
                'slug' => 'anti-arnaque',
                'title' => 'Anti-Arnaque',
                'picture' => NULL,
            'content' => '<p><b>Protégez-vous contre la fraude sur Internet!</b></p><p>L\'immense majorité des annonces sont publiées par des personnes honnêtes et de confiance. Vous pouvez donc faire d\'excellentes affaires. Malgré cela, il est important de suivre les quelques règles de bon sens suivantes pour éviter toute tentative d\'arnaque.</p><p><b>Nos conseils</b></p><ul><li>Faîtes des affaires avec des gens que vous pouvez rencontrer en personne.</li><li>N\'envoyez jamais d\'argent par Western Union, MoneyGram ou des systèmes de paiement anonymes.</li><li>N\'envoyez jamais des marchandises ou de l\'argent à l\'étranger.</li><li>N\'acceptez pas de chèques.</li><li>Renseignez-vous sur la personne à laquelle vous avez affaire en confirmant par une autre source son nom, son adresse et son numéro de téléphone.</li><li>Conservez une copie de toutes les correspondances (emails, annonces, lettres, etc.) et coordonnées de la personne.</li><li>Si une affaire semble trop belle pour être vraie, il y a toutes les chances que ce soit le cas. Abstenez-vous.</li></ul><p><b>Reconnaitre une tentative d\'arnaque</b></p><ul><li>La majorité des arnaques ont une ou plusieurs de ces caractéristiques:</li><li>La personne est à l\'étranger ou en déplacement à l\'étranger.</li><li>La personne refuse de vous rencontrer en personne.</li><li>Le paiement est fait par Western Union, Money Gram ou par chèque.</li><li>Les messages sont dans un langage approximatif (que ce soit en anglais ou en français).</li><li>Les textes semblent être copiés-collés.</li><li>L\'affaire semble être trop belle pour être vraie.</li></ul>',
                'external_link' => NULL,
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:31:56',
                'updated_at' => '2017-02-12 23:24:52',
            ),
            8 => 
            array (
                'id' => '9',
                'translation_lang' => 'es',
                'translation_of' => '7',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'Contra el Fraude',
                'slug' => 'contra-el-fraude',
                'title' => 'Contra el Fraude',
                'picture' => NULL,
            'content' => '<p><b>Protect yourself against Internet fraud!</b></p><p>The vast majority of ads are posted by honest people and trust. So you can do excellent business. Despite this, it is important to follow a few common sense rules following to prevent any attempt to scam.</p><p><b>Our advices</b></p><ul><li>Doing business with people you can meet in person.</li><li>Never send money by Western Union, MoneyGram or other anonymous payment systems.</li><li>Never send money or products abroad.</li><li>Do not accept checks.</li><li>Ask about the person you\'re dealing with another confirming source name, address and telephone number.</li><li>Keep copies of all correspondence (emails, ads, letters, etc.) and details of the person.</li><li>If a deal seems too good to be true, there is every chance that this is the case. Refrain.</li></ul><p><b>Recognize attempted scam</b></p><ul><li>The majority of scams have one or more of these characteristics:</li><li>The person is abroad or traveling abroad.</li><li>The person refuses to meet you in person.</li><li>Payment is made through Western Union, Money Gram or check.</li><li>The messages are in broken language (English or French or ...).</li><li>The texts seem to be copied and pasted.</li><li>The deal seems to be too good to be true.</li></ul>',
                'external_link' => NULL,
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:31:56',
                'updated_at' => '2017-02-12 23:24:52',
            ),
            9 => 
            array (
                'id' => '10',
                'translation_lang' => 'en',
                'translation_of' => '10',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'FAQ',
                'slug' => 'faq',
                'title' => 'Frequently Asked Questions',
                'picture' => NULL,
                'content' => '<p><b>How do I place an ad?</b></p><p>It\'s very easy to place an ad: click on the button "Post free Ads" above right.</p><p><b>What does it cost to advertise?</b></p><p>The publication is 100% free throughout the website.</p><p><b>If I post an ad, will I also get more spam e-mails?</b></p><p>Absolutely not because your email address is not visible on the website.</p><p><b>How long will my ad remain on the website?</b></p><p>In general, an ad is automatically deactivated from the website after 3 months. You will receive an email a week before D-Day and another on the day of deactivation. You have the ability to put them online in the following month by logging into your account on the site. After this delay, your ad will be automatically removed permanently from the website.</p><p><b>I sold my item. How do I delete my ad?</b></p><p>Once your product is sold or leased, log in to your account to remove your ad.</p>',
                'external_link' => NULL,
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:34:56',
                'updated_at' => '2017-02-14 08:23:52',
            ),
            10 => 
            array (
                'id' => '11',
                'translation_lang' => 'fr',
                'translation_of' => '10',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'FAQ',
                'slug' => 'faq',
                'title' => 'Foire aux Questions',
                'picture' => NULL,
                'content' => '<p><b>Comment passer une annonce?</b></p><p>Pour passer une annonce c\'est très simple: vous cliquez que le bouton "Publiez une annonce" en haut à droite.</p><p><b>Quel est le coût de la publication?</b></p><p>La publication est 100% gratuite sur l\'ensemble du site.</p><p><b>Si je poste une annonce, vais-je recevoir plus de spams?</b></p><p>Absolument pas car votre adresse email n\'est pas rendu visible sur le site.</p><p><b>Pour combien de temps mon annonce restera sur le site?</b></p><p>En général, une annonce est automatiquement désactivée du site après 3 mois. Vous recevrez un email une semaine précédent le jour-j et un autre le jour même de la désactivation. Vous avez la possibilité de les remettre en ligne dans le mois suivant en vous connectant à votre compte sur le site. Après ce délais, votre annonce sera automatiquement supprimée définitivement du site.</p><p><b>J\'ai vendu mon article. Comment puis-je supprimer mon annonce?</b></p><p>Une fois que votre bien et vendu ou loué, connectez-vous à votre compte pour supprimer votre annonce.</p>',
                'external_link' => NULL,
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:34:56',
                'updated_at' => '2017-02-14 08:23:52',
            ),
            11 => 
            array (
                'id' => '12',
                'translation_lang' => 'es',
                'translation_of' => '10',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'FAQ',
                'slug' => 'faq',
                'title' => 'Preguntas más frecuentes',
                'picture' => NULL,
                'content' => '<p><b>How do I place an ad?</b></p><p>It\'s very easy to place an ad: click on the button "Post free Ads" above right.</p><p><b>What does it cost to advertise?</b></p><p>The publication is 100% free throughout the website.</p><p><b>If I post an ad, will I also get more spam e-mails?</b></p><p>Absolutely not because your email address is not visible on the website.</p><p><b>How long will my ad remain on the website?</b></p><p>In general, an ad is automatically deactivated from the website after 3 months. You will receive an email a week before D-Day and another on the day of deactivation. You have the ability to put them online in the following month by logging into your account on the site. After this delay, your ad will be automatically removed permanently from the website.</p><p><b>I sold my item. How do I delete my ad?</b></p><p>Once your product is sold or leased, log in to your account to remove your ad.</p>',
                'external_link' => NULL,
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-02-10 14:34:56',
                'updated_at' => '2017-02-14 08:23:52',
            ),
            12 => 
            array (
                'id' => '13',
                'translation_lang' => 'ar',
                'translation_of' => '1',
                'parent_id' => '0',
                'type' => 'terms',
                'name' => 'شروط',
                'slug' => 'terms',
                'title' => 'البنود و الظروف',
                'picture' => NULL,
            'content' => '<h4><b>Definitions</b></h4><p>Each of the terms mentioned below have in these Conditions of Sale JobClass Service (hereinafter the "Conditions") the following meanings:</p><ol><li>Announcement&nbsp;: refers to all the elements and data (visual, textual, sound, photographs, drawings), presented by an Advertiser editorial under his sole responsibility, in order to buy, rent or sell a product or service and broadcast on the Website and Mobile Site.</li><li>Advertiser&nbsp;: means any natural or legal person, a major, established in France, holds an account and having submitted an announcement, from it, on the Website. Any Advertiser must be connected to the Personal Account for deposit and or manage its ads. Ad first deposit automatically entails the establishment of a Personal Account to the Advertiser.</li><li>Personal Account&nbsp;: refers to the free space than any Advertiser must create and which it should connect from the Website to disseminate, manage and view its ads.</li><li>JobClass&nbsp;: means the company that publishes and operates the Website and Mobile Site {YourCompany}, registered at the Trade and Companies Register of Cotonou under the number {YourCompany Registration Number} whose registered office is at {YourCompany Address}.</li><li>Customer Service&nbsp;: JobClass means the department to which the Advertiser may obtain further information. This service can be contacted via email by clicking the link on the Website and Mobile Site.</li><li>JobClass Service&nbsp;: JobClass means the services made available to Users and Advertisers on the Website and Mobile Site.</li><li>Website&nbsp;: means the website operated by JobClass accessed mainly from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access the Service via internet JobClass.</li><li>Mobile Site&nbsp;: is the mobile site operated by JobClass accessible from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access via their mobile phone service {YourSiteName}.</li><li>User&nbsp;: any visitor with access to JobClass Service via the Website and Mobile Site and Consultant Service JobClass accessible from different media.</li></ol><h4><b>Subject</b></h4><p>These Terms and Conditions Of Use establish the contractual conditions applicable to any subscription by an Advertiser connected to its Personal Account from the Website and Mobile Site.<br></p><h4><b>Acceptance</b></h4><p>Any use of the website by an Advertiser is full acceptance of the current Terms.<br></p><h4><b>Responsibility</b></h4><p>Responsibility for JobClass can not be held liable for non-performance or improper performance of due control, either because of the Advertiser, or a case of major force.<br></p><h4><b>Modification of these terms</b></h4><p>JobClass reserves the right, at any time, to modify all or part of the Terms and Conditions.</p><p>Advertisers are advised to consult the Terms to be aware of the changes.</p><h4><b>Miscellaneous</b></h4><p>If part of the Terms should be illegal, invalid or unenforceable for any reason whatsoever, the provisions in question would be deemed unwritten, without questioning the validity of the remaining provisions will continue to apply between Advertisers and JobClass.</p><p>Any complaints should be addressed to Customer Service JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-11-14 14:52:55',
                'updated_at' => '2017-11-14 14:52:55',
            ),
            13 => 
            array (
                'id' => '14',
                'translation_lang' => 'ar',
                'translation_of' => '4',
                'parent_id' => '0',
                'type' => 'privacy',
                'name' => 'الإجمالية',
                'slug' => 'privacy',
                'title' => 'الإجمالية',
                'picture' => NULL,
            'content' => '<p>Your privacy is an important part of our relationship with you. Protecting your privacy is only part of our mission to provide a secure web environment. When using our site, including our services, your information will remain strictly confidential. Contributions made on our blog or on our forum are open to public view; so please do not post any personal information in your dealings with others. We accept no liability for those actions because it is your sole responsibility to adequate and safe post content on our site. We will not share, rent or share your information with third parties.</p><p>When you visit our site, we collect technical information about your computer and how you access our website and analyze this information such as Internet Protocol (IP) address of your computer, the operating system used by your computer, the browser (eg, Chrome, Firefox, Internet Explorer or other) your computer uses, the name of your Internet service provider (ISP), the Uniform Resource Locator (URL) of the website from which you come and the URL to which you go next and certain operating metrics such as the number of times you use our website. This general information can be used to help us better understand how our site is viewed and used. We may share this general information about our site with our business partners or the general public. For example, we may share the information on the number of daily unique visitors to our site with potential corporate partners or use them for advertising purposes. This information does contain any of your personal data that can be used to contact you or identify you.</p><p>When we place links or banners to other sites of our website, please note that we do not control this kind of content or practices or privacy policies of those sites. We do not endorse or assume no responsibility for the privacy policies or information collection practices of any other website other than managed sites JobClass.</p><p>We use the highest security standard available to protect your identifiable information in transit to us. All data stored on our servers are protected by a secure firewall for the unauthorized use or activity can not take place. Although we make every effort to protect your personal information against loss, misuse or alteration by third parties, you should be aware that there is always a risk that low-intentioned manage to find a way to thwart our security system or that Internet transmissions could be intercepted.</p><p>We reserve the right, without notice, to change, modify, add or remove portions of our Privacy Policy at any time and from time to time. These changes will be posted publicly on our website. When you visit our website, you accept all the terms of our privacy policy. Your continued use of this website constitutes your continued agreement to these terms. If you do not agree with the terms of our privacy policy, you should cease using our website.</p>',
                'external_link' => NULL,
                'lft' => '8',
                'rgt' => '9',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-11-14 14:52:55',
                'updated_at' => '2017-11-14 14:52:55',
            ),
            14 => 
            array (
                'id' => '15',
                'translation_lang' => 'ar',
                'translation_of' => '7',
                'parent_id' => '0',
                'type' => 'tips',
                'name' => 'مكافحة الغش',
                'slug' => 'anti-scam',
                'title' => 'مكافحة الغش',
                'picture' => NULL,
            'content' => '<p><b>Protect yourself against Internet fraud!</b></p><p>The vast majority of ads are posted by honest people and trust. So you can do excellent business. Despite this, it is important to follow a few common sense rules following to prevent any attempt to scam.</p><p><b>Our advices</b></p><ul><li>Doing business with people you can meet in person.</li><li>Never send money by Western Union, MoneyGram or other anonymous payment systems.</li><li>Never send money or products abroad.</li><li>Do not accept checks.</li><li>Ask about the person you\'re dealing with another confirming source name, address and telephone number.</li><li>Keep copies of all correspondence (emails, ads, letters, etc.) and details of the person.</li><li>If a deal seems too good to be true, there is every chance that this is the case. Refrain.</li></ul><p><b>Recognize attempted scam</b></p><ul><li>The majority of scams have one or more of these characteristics:</li><li>The person is abroad or traveling abroad.</li><li>The person refuses to meet you in person.</li><li>Payment is made through Western Union, Money Gram or check.</li><li>The messages are in broken language (English or French or ...).</li><li>The texts seem to be copied and pasted.</li><li>The deal seems to be too good to be true.</li></ul>',
                'external_link' => NULL,
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-11-14 14:52:55',
                'updated_at' => '2017-11-14 14:52:55',
            ),
            15 => 
            array (
                'id' => '16',
                'translation_lang' => 'ar',
                'translation_of' => '10',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'التعليمات',
                'slug' => 'faq',
                'title' => 'أسئلة مكررة',
                'picture' => NULL,
                'content' => '<p><b>How do I place an ad?</b></p><p>It\'s very easy to place an ad: click on the button "Post free Ads" above right.</p><p><b>What does it cost to advertise?</b></p><p>The publication is 100% free throughout the website.</p><p><b>If I post an ad, will I also get more spam e-mails?</b></p><p>Absolutely not because your email address is not visible on the website.</p><p><b>How long will my ad remain on the website?</b></p><p>In general, an ad is automatically deactivated from the website after 3 months. You will receive an email a week before D-Day and another on the day of deactivation. You have the ability to put them online in the following month by logging into your account on the site. After this delay, your ad will be automatically removed permanently from the website.</p><p><b>I sold my item. How do I delete my ad?</b></p><p>Once your product is sold or leased, log in to your account to remove your ad.</p>',
                'external_link' => NULL,
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2017-11-14 14:52:55',
                'updated_at' => '2017-11-14 14:52:55',
            ),
            16 => 
            array (
                'id' => '17',
                'translation_lang' => 'de',
                'translation_of' => '1',
                'parent_id' => '0',
                'type' => 'terms',
                'name' => 'Terms',
                'slug' => 'terms',
                'title' => 'Terms & Conditions',
                'picture' => NULL,
            'content' => '<h4><b>Definitions</b></h4><p>Each of the terms mentioned below have in these Conditions of Sale JobClass Service (hereinafter the "Conditions") the following meanings:</p><ol><li>Announcement&nbsp;: refers to all the elements and data (visual, textual, sound, photographs, drawings), presented by an Advertiser editorial under his sole responsibility, in order to buy, rent or sell a product or service and broadcast on the Website and Mobile Site.</li><li>Advertiser&nbsp;: means any natural or legal person, a major, established in France, holds an account and having submitted an announcement, from it, on the Website. Any Advertiser must be connected to the Personal Account for deposit and or manage its ads. Ad first deposit automatically entails the establishment of a Personal Account to the Advertiser.</li><li>Personal Account&nbsp;: refers to the free space than any Advertiser must create and which it should connect from the Website to disseminate, manage and view its ads.</li><li>JobClass&nbsp;: means the company that publishes and operates the Website and Mobile Site {YourCompany}, registered at the Trade and Companies Register of Cotonou under the number {YourCompany Registration Number} whose registered office is at {YourCompany Address}.</li><li>Customer Service&nbsp;: JobClass means the department to which the Advertiser may obtain further information. This service can be contacted via email by clicking the link on the Website and Mobile Site.</li><li>JobClass Service&nbsp;: JobClass means the services made available to Users and Advertisers on the Website and Mobile Site.</li><li>Website&nbsp;: means the website operated by JobClass accessed mainly from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access the Service via internet JobClass.</li><li>Mobile Site&nbsp;: is the mobile site operated by JobClass accessible from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access via their mobile phone service {YourSiteName}.</li><li>User&nbsp;: any visitor with access to JobClass Service via the Website and Mobile Site and Consultant Service JobClass accessible from different media.</li></ol><h4><b>Subject</b></h4><p>These Terms and Conditions Of Use establish the contractual conditions applicable to any subscription by an Advertiser connected to its Personal Account from the Website and Mobile Site.<br></p><h4><b>Acceptance</b></h4><p>Any use of the website by an Advertiser is full acceptance of the current Terms.<br></p><h4><b>Responsibility</b></h4><p>Responsibility for JobClass can not be held liable for non-performance or improper performance of due control, either because of the Advertiser, or a case of major force.<br></p><h4><b>Modification of these terms</b></h4><p>JobClass reserves the right, at any time, to modify all or part of the Terms and Conditions.</p><p>Advertisers are advised to consult the Terms to be aware of the changes.</p><h4><b>Miscellaneous</b></h4><p>If part of the Terms should be illegal, invalid or unenforceable for any reason whatsoever, the provisions in question would be deemed unwritten, without questioning the validity of the remaining provisions will continue to apply between Advertisers and JobClass.</p><p>Any complaints should be addressed to Customer Service JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2018-03-20 16:06:43',
                'updated_at' => '2018-03-20 16:06:43',
            ),
            17 => 
            array (
                'id' => '18',
                'translation_lang' => 'de',
                'translation_of' => '4',
                'parent_id' => '0',
                'type' => 'privacy',
                'name' => 'Privacy',
                'slug' => 'privacy',
                'title' => 'Privacy',
                'picture' => NULL,
            'content' => '<p>Your privacy is an important part of our relationship with you. Protecting your privacy is only part of our mission to provide a secure web environment. When using our site, including our services, your information will remain strictly confidential. Contributions made on our blog or on our forum are open to public view; so please do not post any personal information in your dealings with others. We accept no liability for those actions because it is your sole responsibility to adequate and safe post content on our site. We will not share, rent or share your information with third parties.</p><p>When you visit our site, we collect technical information about your computer and how you access our website and analyze this information such as Internet Protocol (IP) address of your computer, the operating system used by your computer, the browser (eg, Chrome, Firefox, Internet Explorer or other) your computer uses, the name of your Internet service provider (ISP), the Uniform Resource Locator (URL) of the website from which you come and the URL to which you go next and certain operating metrics such as the number of times you use our website. This general information can be used to help us better understand how our site is viewed and used. We may share this general information about our site with our business partners or the general public. For example, we may share the information on the number of daily unique visitors to our site with potential corporate partners or use them for advertising purposes. This information does contain any of your personal data that can be used to contact you or identify you.</p><p>When we place links or banners to other sites of our website, please note that we do not control this kind of content or practices or privacy policies of those sites. We do not endorse or assume no responsibility for the privacy policies or information collection practices of any other website other than managed sites JobClass.</p><p>We use the highest security standard available to protect your identifiable information in transit to us. All data stored on our servers are protected by a secure firewall for the unauthorized use or activity can not take place. Although we make every effort to protect your personal information against loss, misuse or alteration by third parties, you should be aware that there is always a risk that low-intentioned manage to find a way to thwart our security system or that Internet transmissions could be intercepted.</p><p>We reserve the right, without notice, to change, modify, add or remove portions of our Privacy Policy at any time and from time to time. These changes will be posted publicly on our website. When you visit our website, you accept all the terms of our privacy policy. Your continued use of this website constitutes your continued agreement to these terms. If you do not agree with the terms of our privacy policy, you should cease using our website.</p>',
                'external_link' => NULL,
                'lft' => '8',
                'rgt' => '9',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2018-03-20 16:06:43',
                'updated_at' => '2018-03-20 16:06:43',
            ),
            18 => 
            array (
                'id' => '19',
                'translation_lang' => 'de',
                'translation_of' => '7',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'Anti-Scam',
                'slug' => 'anti-scam',
                'title' => 'Anti-Scam',
                'picture' => NULL,
            'content' => '<p><b>Protect yourself against Internet fraud!</b></p><p>The vast majority of ads are posted by honest people and trust. So you can do excellent business. Despite this, it is important to follow a few common sense rules following to prevent any attempt to scam.</p><p><b>Our advices</b></p><ul><li>Doing business with people you can meet in person.</li><li>Never send money by Western Union, MoneyGram or other anonymous payment systems.</li><li>Never send money or products abroad.</li><li>Do not accept checks.</li><li>Ask about the person you\'re dealing with another confirming source name, address and telephone number.</li><li>Keep copies of all correspondence (emails, ads, letters, etc.) and details of the person.</li><li>If a deal seems too good to be true, there is every chance that this is the case. Refrain.</li></ul><p><b>Recognize attempted scam</b></p><ul><li>The majority of scams have one or more of these characteristics:</li><li>The person is abroad or traveling abroad.</li><li>The person refuses to meet you in person.</li><li>Payment is made through Western Union, Money Gram or check.</li><li>The messages are in broken language (English or French or ...).</li><li>The texts seem to be copied and pasted.</li><li>The deal seems to be too good to be true.</li></ul>',
                'external_link' => NULL,
                'lft' => '4',
                'rgt' => '5',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2018-03-20 16:06:43',
                'updated_at' => '2018-03-20 16:06:43',
            ),
            19 => 
            array (
                'id' => '20',
                'translation_lang' => 'de',
                'translation_of' => '10',
                'parent_id' => '0',
                'type' => 'standard',
                'name' => 'FAQ',
                'slug' => 'faq',
                'title' => 'Frequently Asked Questions',
                'picture' => NULL,
                'content' => '<p><b>How do I place an ad?</b></p><p>It\'s very easy to place an ad: click on the button "Post free Ads" above right.</p><p><b>What does it cost to advertise?</b></p><p>The publication is 100% free throughout the website.</p><p><b>If I post an ad, will I also get more spam e-mails?</b></p><p>Absolutely not because your email address is not visible on the website.</p><p><b>How long will my ad remain on the website?</b></p><p>In general, an ad is automatically deactivated from the website after 3 months. You will receive an email a week before D-Day and another on the day of deactivation. You have the ability to put them online in the following month by logging into your account on the site. After this delay, your ad will be automatically removed permanently from the website.</p><p><b>I sold my item. How do I delete my ad?</b></p><p>Once your product is sold or leased, log in to your account to remove your ad.</p>',
                'external_link' => NULL,
                'lft' => '2',
                'rgt' => '3',
                'depth' => '1',
                'name_color' => NULL,
                'title_color' => NULL,
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2018-03-20 16:06:43',
                'updated_at' => '2018-03-20 16:06:43',
            ),
            20 => 
            array (
                'id' => '21',
                'translation_lang' => 'en',
                'translation_of' => '21',
                'parent_id' => NULL,
                'type' => 'termsclient',
                'name' => 'TermsClient',
                'slug' => 'termsclient',
                'title' => 'Terms and Conditions for Clients',
                'picture' => NULL,
            'content' => '<h4><b>Definitions</b></h4><p>Each of the terms mentioned below have in these Conditions of Sale JobClass Service (hereinafter the "Conditions") the following meanings:</p><ol><li>Announcement&nbsp;: refers to all the elements and data (visual, textual, sound, photographs, drawings), presented by an Advertiser editorial under his sole responsibility, in order to buy, rent or sell a product or service and broadcast on the Website and Mobile Site.</li><li>Advertiser&nbsp;: means any natural or legal person, a major, established in France, holds an account and having submitted an announcement, from it, on the Website. Any Advertiser must be connected to the Personal Account for deposit and or manage its ads. Ad first deposit automatically entails the establishment of a Personal Account to the Advertiser.</li><li>Personal Account&nbsp;: refers to the free space than any Advertiser must create and which it should connect from the Website to disseminate, manage and view its ads.</li><li>JobClass&nbsp;: means the company that publishes and operates the Website and Mobile Site {YourCompany}, registered at the Trade and Companies Register of Cotonou under the number {YourCompany Registration Number} whose registered office is at {YourCompany Address}.</li><li>Customer Service&nbsp;: JobClass means the department to which the Advertiser may obtain further information. This service can be contacted via email by clicking the link on the Website and Mobile Site.</li><li>JobClass Service&nbsp;: JobClass means the services made available to Users and Advertisers on the Website and Mobile Site.</li><li>Website&nbsp;: means the website operated by JobClass accessed mainly from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access the Service via internet JobClass.</li><li>Mobile Site&nbsp;: is the mobile site operated by JobClass accessible from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access via their mobile phone service {YourSiteName}.</li><li>User&nbsp;: any visitor with access to JobClass Service via the Website and Mobile Site and Consultant Service JobClass accessible from different media.</li></ol><h4><b>Subject</b></h4><p>These Terms and Conditions Of Use establish the contractual conditions applicable to any subscription by an Advertiser connected to its Personal Account from the Website and Mobile Site.<br></p><h4><b>Acceptance</b></h4><p>Any use of the website by an Advertiser is full acceptance of the current Terms.<br></p><h4><b>Responsibility</b></h4><p>Responsibility for JobClass can not be held liable for non-performance or improper performance of due control, either because of the Advertiser, or a case of major force.<br></p><h4><b>Modification of these terms</b></h4><p>JobClass reserves the right, at any time, to modify all or part of the Terms and Conditions.</p><p>Advertisers are advised to consult the Terms to be aware of the changes.</p><h4><b>Miscellaneous</b></h4><p>If part of the Terms should be illegal, invalid or unenforceable for any reason whatsoever, the provisions in question would be deemed unwritten, without questioning the validity of the remaining provisions will continue to apply between Advertisers and JobClass.</p><p>Any complaints should be addressed to Customer Service JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => '#b38b8b',
                'title_color' => '#451d1d',
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2018-04-27 15:53:27',
                'updated_at' => '2018-04-27 15:58:21',
            ),
            21 => 
            array (
                'id' => '22',
                'translation_lang' => 'fr',
                'translation_of' => '21',
                'parent_id' => NULL,
                'type' => 'termsclient',
                'name' => 'TermsClient',
                'slug' => 'termsclient',
                'title' => 'Terms and Conditions for Clients',
                'picture' => NULL,
            'content' => '<h4><b>Definitions</b></h4><p>Each of the terms mentioned below have in these Conditions of Sale JobClass Service (hereinafter the "Conditions") the following meanings:</p><ol><li>Announcement&nbsp;: refers to all the elements and data (visual, textual, sound, photographs, drawings), presented by an Advertiser editorial under his sole responsibility, in order to buy, rent or sell a product or service and broadcast on the Website and Mobile Site.</li><li>Advertiser&nbsp;: means any natural or legal person, a major, established in France, holds an account and having submitted an announcement, from it, on the Website. Any Advertiser must be connected to the Personal Account for deposit and or manage its ads. Ad first deposit automatically entails the establishment of a Personal Account to the Advertiser.</li><li>Personal Account&nbsp;: refers to the free space than any Advertiser must create and which it should connect from the Website to disseminate, manage and view its ads.</li><li>JobClass&nbsp;: means the company that publishes and operates the Website and Mobile Site {YourCompany}, registered at the Trade and Companies Register of Cotonou under the number {YourCompany Registration Number} whose registered office is at {YourCompany Address}.</li><li>Customer Service&nbsp;: JobClass means the department to which the Advertiser may obtain further information. This service can be contacted via email by clicking the link on the Website and Mobile Site.</li><li>JobClass Service&nbsp;: JobClass means the services made available to Users and Advertisers on the Website and Mobile Site.</li><li>Website&nbsp;: means the website operated by JobClass accessed mainly from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access the Service via internet JobClass.</li><li>Mobile Site&nbsp;: is the mobile site operated by JobClass accessible from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access via their mobile phone service {YourSiteName}.</li><li>User&nbsp;: any visitor with access to JobClass Service via the Website and Mobile Site and Consultant Service JobClass accessible from different media.</li></ol><h4><b>Subject</b></h4><p>These Terms and Conditions Of Use establish the contractual conditions applicable to any subscription by an Advertiser connected to its Personal Account from the Website and Mobile Site.<br></p><h4><b>Acceptance</b></h4><p>Any use of the website by an Advertiser is full acceptance of the current Terms.<br></p><h4><b>Responsibility</b></h4><p>Responsibility for JobClass can not be held liable for non-performance or improper performance of due control, either because of the Advertiser, or a case of major force.<br></p><h4><b>Modification of these terms</b></h4><p>JobClass reserves the right, at any time, to modify all or part of the Terms and Conditions.</p><p>Advertisers are advised to consult the Terms to be aware of the changes.</p><h4><b>Miscellaneous</b></h4><p>If part of the Terms should be illegal, invalid or unenforceable for any reason whatsoever, the provisions in question would be deemed unwritten, without questioning the validity of the remaining provisions will continue to apply between Advertisers and JobClass.</p><p>Any complaints should be addressed to Customer Service JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => '#b38b8b',
                'title_color' => '#451d1d',
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2018-04-27 15:53:27',
                'updated_at' => '2018-04-27 15:53:27',
            ),
            22 => 
            array (
                'id' => '23',
                'translation_lang' => 'es',
                'translation_of' => '21',
                'parent_id' => NULL,
                'type' => 'termsclient',
                'name' => 'TermsClient',
                'slug' => 'termsclient',
                'title' => 'Terms and Conditions for Clients',
                'picture' => NULL,
            'content' => '<h4><b>Definitions</b></h4><p>Each of the terms mentioned below have in these Conditions of Sale JobClass Service (hereinafter the "Conditions") the following meanings:</p><ol><li>Announcement&nbsp;: refers to all the elements and data (visual, textual, sound, photographs, drawings), presented by an Advertiser editorial under his sole responsibility, in order to buy, rent or sell a product or service and broadcast on the Website and Mobile Site.</li><li>Advertiser&nbsp;: means any natural or legal person, a major, established in France, holds an account and having submitted an announcement, from it, on the Website. Any Advertiser must be connected to the Personal Account for deposit and or manage its ads. Ad first deposit automatically entails the establishment of a Personal Account to the Advertiser.</li><li>Personal Account&nbsp;: refers to the free space than any Advertiser must create and which it should connect from the Website to disseminate, manage and view its ads.</li><li>JobClass&nbsp;: means the company that publishes and operates the Website and Mobile Site {YourCompany}, registered at the Trade and Companies Register of Cotonou under the number {YourCompany Registration Number} whose registered office is at {YourCompany Address}.</li><li>Customer Service&nbsp;: JobClass means the department to which the Advertiser may obtain further information. This service can be contacted via email by clicking the link on the Website and Mobile Site.</li><li>JobClass Service&nbsp;: JobClass means the services made available to Users and Advertisers on the Website and Mobile Site.</li><li>Website&nbsp;: means the website operated by JobClass accessed mainly from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access the Service via internet JobClass.</li><li>Mobile Site&nbsp;: is the mobile site operated by JobClass accessible from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access via their mobile phone service {YourSiteName}.</li><li>User&nbsp;: any visitor with access to JobClass Service via the Website and Mobile Site and Consultant Service JobClass accessible from different media.</li></ol><h4><b>Subject</b></h4><p>These Terms and Conditions Of Use establish the contractual conditions applicable to any subscription by an Advertiser connected to its Personal Account from the Website and Mobile Site.<br></p><h4><b>Acceptance</b></h4><p>Any use of the website by an Advertiser is full acceptance of the current Terms.<br></p><h4><b>Responsibility</b></h4><p>Responsibility for JobClass can not be held liable for non-performance or improper performance of due control, either because of the Advertiser, or a case of major force.<br></p><h4><b>Modification of these terms</b></h4><p>JobClass reserves the right, at any time, to modify all or part of the Terms and Conditions.</p><p>Advertisers are advised to consult the Terms to be aware of the changes.</p><h4><b>Miscellaneous</b></h4><p>If part of the Terms should be illegal, invalid or unenforceable for any reason whatsoever, the provisions in question would be deemed unwritten, without questioning the validity of the remaining provisions will continue to apply between Advertisers and JobClass.</p><p>Any complaints should be addressed to Customer Service JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => '#b38b8b',
                'title_color' => '#451d1d',
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2018-04-27 15:53:27',
                'updated_at' => '2018-04-27 15:53:27',
            ),
            23 => 
            array (
                'id' => '24',
                'translation_lang' => 'de',
                'translation_of' => '21',
                'parent_id' => NULL,
                'type' => 'termsclient',
                'name' => 'TermsClient',
                'slug' => 'termsclient',
                'title' => 'Terms and Conditions for Clients',
                'picture' => NULL,
            'content' => '<h4><b>Definitions</b></h4><p>Each of the terms mentioned below have in these Conditions of Sale JobClass Service (hereinafter the "Conditions") the following meanings:</p><ol><li>Announcement&nbsp;: refers to all the elements and data (visual, textual, sound, photographs, drawings), presented by an Advertiser editorial under his sole responsibility, in order to buy, rent or sell a product or service and broadcast on the Website and Mobile Site.</li><li>Advertiser&nbsp;: means any natural or legal person, a major, established in France, holds an account and having submitted an announcement, from it, on the Website. Any Advertiser must be connected to the Personal Account for deposit and or manage its ads. Ad first deposit automatically entails the establishment of a Personal Account to the Advertiser.</li><li>Personal Account&nbsp;: refers to the free space than any Advertiser must create and which it should connect from the Website to disseminate, manage and view its ads.</li><li>JobClass&nbsp;: means the company that publishes and operates the Website and Mobile Site {YourCompany}, registered at the Trade and Companies Register of Cotonou under the number {YourCompany Registration Number} whose registered office is at {YourCompany Address}.</li><li>Customer Service&nbsp;: JobClass means the department to which the Advertiser may obtain further information. This service can be contacted via email by clicking the link on the Website and Mobile Site.</li><li>JobClass Service&nbsp;: JobClass means the services made available to Users and Advertisers on the Website and Mobile Site.</li><li>Website&nbsp;: means the website operated by JobClass accessed mainly from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access the Service via internet JobClass.</li><li>Mobile Site&nbsp;: is the mobile site operated by JobClass accessible from the URL <a href="http://www.bedigit.com">http://www.bedigit.com</a> and allowing Users and Advertisers to access via their mobile phone service {YourSiteName}.</li><li>User&nbsp;: any visitor with access to JobClass Service via the Website and Mobile Site and Consultant Service JobClass accessible from different media.</li></ol><h4><b>Subject</b></h4><p>These Terms and Conditions Of Use establish the contractual conditions applicable to any subscription by an Advertiser connected to its Personal Account from the Website and Mobile Site.<br></p><h4><b>Acceptance</b></h4><p>Any use of the website by an Advertiser is full acceptance of the current Terms.<br></p><h4><b>Responsibility</b></h4><p>Responsibility for JobClass can not be held liable for non-performance or improper performance of due control, either because of the Advertiser, or a case of major force.<br></p><h4><b>Modification of these terms</b></h4><p>JobClass reserves the right, at any time, to modify all or part of the Terms and Conditions.</p><p>Advertisers are advised to consult the Terms to be aware of the changes.</p><h4><b>Miscellaneous</b></h4><p>If part of the Terms should be illegal, invalid or unenforceable for any reason whatsoever, the provisions in question would be deemed unwritten, without questioning the validity of the remaining provisions will continue to apply between Advertisers and JobClass.</p><p>Any complaints should be addressed to Customer Service JobClass.</p>',
                'external_link' => NULL,
                'lft' => '6',
                'rgt' => '7',
                'depth' => '1',
                'name_color' => '#b38b8b',
                'title_color' => '#451d1d',
                'target_blank' => '0',
                'excluded_from_footer' => '0',
                'active' => '1',
                'created_at' => '2018-04-27 15:53:27',
                'updated_at' => '2018-04-27 15:53:27',
            ),
        ));
        
        
    }
}