<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => '1',
                'country_code' => 'AT',
                'user_type_id' => '1',
                'gender_id' => '1',
                'name' => 'mm',
                'about' => 'Administrator',
                'phone' => '+4312345678',
                'phone_hidden' => '0',
                'username' => 'itellicomm',
                'email' => 'admin@itellico.com',
                'password' => '$2y$10$F1fG7B/uB8UKSoBWFDJqW.Vfj7bTWFesaB6XbzlEJC1eK3DDIQVA2',
                'remember_token' => 'OHpVWTkbC4Efwdvw2jvZEsB9gJlWveHAxhgbeu6iHP595lZHgNhBHmVXD4Cw',
                'is_admin' => '1',
                'active' => '1',
                'lang_locale' => '2',
                'can_be_impersonated' => '1',
                'disable_comments' => '0',
                'receive_newsletter' => NULL,
                'receive_advice' => NULL,
                'ip_addr' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'email_token' => NULL,
                'phone_token' => NULL,
                'verified_email' => '1',
                'verified_phone' => '1',
                'blocked' => '0',
                'closed' => '0',
                'last_login_at' => '2018-03-26 15:28:47',
                'created_at' => NULL,
                'updated_at' => '2018-03-26 13:28:47',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => '3',
                'country_code' => 'HU',
                'user_type_id' => '1',
                'gender_id' => '1',
                'name' => 'Peter',
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => '0',
                'username' => NULL,
                'email' => 'honti.peter@voov.hu',
                'password' => '$2y$10$Rs0Yn/Arbeo8LY4oPATY6OI0ICLf265MOjYyE6lqdsSttrEX0ZiR.',
                'remember_token' => NULL,
                'is_admin' => '1',
                'active' => '1',
                'lang_locale' => NULL,
                'can_be_impersonated' => '1',
                'disable_comments' => '0',
                'receive_newsletter' => '1',
                'receive_advice' => '1',
                'ip_addr' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'email_token' => NULL,
                'phone_token' => NULL,
                'verified_email' => '0',
                'verified_phone' => '1',
                'blocked' => '0',
                'closed' => '0',
                'last_login_at' => NULL,
                'created_at' => '2018-03-20 13:09:27',
                'updated_at' => '2018-03-20 15:11:57',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => '5',
                'country_code' => 'AT',
                'user_type_id' => '3',
                'gender_id' => '1',
                'name' => 'Katharina model',
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => '0',
                'username' => NULL,
                'email' => 'modelkathi@beta.go-models.com',
                'password' => '$2y$10$OpZz05IgYLixWT6KTg5QPuOEZRkvCT.Trqua2TbsLLjgHayoYEX6u',
                'remember_token' => '4ZvtlARqVCEDGMXvbIT76HDCsr6CFGqameTfYQ0JL8dQXQk0OWTo8RF1PCIB',
                'is_admin' => '0',
                'active' => '1',
                'lang_locale' => NULL,
                'can_be_impersonated' => '1',
                'disable_comments' => '0',
                'receive_newsletter' => '1',
                'receive_advice' => '1',
                'ip_addr' => '185.143.182.1',
                'provider' => NULL,
                'provider_id' => NULL,
                'email_token' => NULL,
                'phone_token' => NULL,
                'verified_email' => '1',
                'verified_phone' => '1',
                'blocked' => '0',
                'closed' => '0',
                'last_login_at' => NULL,
                'created_at' => '2018-03-21 22:00:58',
                'updated_at' => '2018-03-21 22:08:43',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => '6',
                'country_code' => 'AT',
                'user_type_id' => '2',
                'gender_id' => NULL,
                'name' => 'Katharinapartner',
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => NULL,
                'username' => NULL,
                'email' => 'kathipartner@beta.go-models.com',
                'password' => '$2y$10$tO6WIU50v2Rgcw6LqGTGKeuijdH.NHGX4IBTTDx5WnAWVK9nPZSwO',
                'remember_token' => 'jAJNXzS9inHLUxs7oeDJVd5zyQ02TfMucuFSkcRTHjkJ6Fz2A3u2SyDFyly3',
                'is_admin' => '0',
                'active' => '1',
                'lang_locale' => NULL,
                'can_be_impersonated' => '1',
                'disable_comments' => '0',
                'receive_newsletter' => '1',
                'receive_advice' => '1',
                'ip_addr' => '185.143.182.1',
                'provider' => NULL,
                'provider_id' => NULL,
                'email_token' => NULL,
                'phone_token' => NULL,
                'verified_email' => '1',
                'verified_phone' => '1',
                'blocked' => '0',
                'closed' => '0',
                'last_login_at' => '2018-03-21 21:58:27',
                'created_at' => '2018-03-21 22:02:15',
                'updated_at' => '2018-03-21 22:58:27',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => '7',
                'country_code' => 'AT',
                'user_type_id' => '3',
                'gender_id' => '2',
                'name' => 'katharinamodel',
                'about' => NULL,
                'phone' => '+436506476812',
                'phone_hidden' => '1',
                'username' => 'kathi',
                'email' => 'kathimodel@beta.go-models.com',
                'password' => '$2y$10$vOH15DI2e1.4nVsP8AIWh.HPuSfRZwZtfGpS0ZqZJSEYyjCoiFii6',
                'remember_token' => 'feU3uha7vLxGYpCQ6bCnB0eNW0hZ6nQIW6MnQgYWlu1cmQipWqCiaqDD3Sh7',
                'is_admin' => '0',
                'active' => '1',
                'lang_locale' => NULL,
                'can_be_impersonated' => '1',
                'disable_comments' => '0',
                'receive_newsletter' => NULL,
                'receive_advice' => NULL,
                'ip_addr' => '185.143.182.1',
                'provider' => NULL,
                'provider_id' => NULL,
                'email_token' => NULL,
                'phone_token' => NULL,
                'verified_email' => '1',
                'verified_phone' => '1',
                'blocked' => '0',
                'closed' => '0',
                'last_login_at' => '2018-03-21 21:51:55',
                'created_at' => '2018-03-21 22:33:18',
                'updated_at' => '2018-03-21 22:51:55',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => '8',
                'country_code' => 'AT',
                'user_type_id' => '1',
                'gender_id' => '1',
                'name' => 'Kathi',
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => '0',
                'username' => NULL,
                'email' => 'ke@go-models.com',
                'password' => '$2y$10$5GuZSlVzlM6bwGbc0KXUBetBHfL6g7WXKnK83zfU9DpmybsKCho/O',
                'remember_token' => NULL,
                'is_admin' => '1',
                'active' => '1',
                'lang_locale' => NULL,
                'can_be_impersonated' => '1',
                'disable_comments' => '0',
                'receive_newsletter' => '1',
                'receive_advice' => '1',
                'ip_addr' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'email_token' => NULL,
                'phone_token' => NULL,
                'verified_email' => '1',
                'verified_phone' => '1',
                'blocked' => '0',
                'closed' => '0',
                'last_login_at' => NULL,
                'created_at' => '2018-03-21 22:44:05',
                'updated_at' => '2018-03-21 22:44:05',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => '9',
                'country_code' => 'LI',
                'user_type_id' => '4',
                'gender_id' => '1',
                'name' => 'Artem',
                'about' => NULL,
                'phone' => NULL,
                'phone_hidden' => '0',
                'username' => NULL,
                'email' => 'artem@artem.testmail.go-models.com',
                'password' => '$2y$10$ILlnQmaEAVEIfqhGw3MO/upDSBaUMowD..jppilt/mEmO7/xNSw7G',
                'remember_token' => 'h6oUliAGVEDnZBS0xFrLw9jWLIqLdzYJUE8yFi1R8NtyA7Y0SzQDCFwW6eKC',
                'is_admin' => '0',
                'active' => '1',
                'lang_locale' => '2',
                'can_be_impersonated' => '1',
                'disable_comments' => '0',
                'receive_newsletter' => '1',
                'receive_advice' => '1',
                'ip_addr' => '185.6.127.233',
                'provider' => NULL,
                'provider_id' => NULL,
                'email_token' => NULL,
                'phone_token' => NULL,
                'verified_email' => '1',
                'verified_phone' => '1',
                'blocked' => '0',
                'closed' => '0',
                'last_login_at' => '2018-03-24 00:31:33',
                'created_at' => '2018-03-23 19:52:28',
                'updated_at' => '2018-03-23 23:31:33',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}