ALTER TABLE `user_address` ADD INDEX (`user_id`);
ALTER TABLE `user_profile` ADD INDEX (`user_id`);
ALTER TABLE `valid_values` ADD INDEX (`type`);
ALTER TABLE `blog_categories` ADD INDEX (`active`);
ALTER TABLE `blog_entries` ADD INDEX (`category_id`);
ALTER TABLE `blog_entries` ADD INDEX (`slug`);
ALTER TABLE `blog_entries` ADD INDEX (`active`);
ALTER TABLE `blog_entries` ADD INDEX (`featured`);
ALTER TABLE `blog_tags` ADD INDEX (`slug`);
ALTER TABLE `branches` ADD INDEX (`type`);
ALTER TABLE `branches` ADD INDEX (`active`);
ALTER TABLE `categories` ADD INDEX (`type`);
ALTER TABLE `categories` ADD INDEX (`active`);
ALTER TABLE `invitations` ADD INDEX (`status`);
ALTER TABLE `messages` ADD INDEX (`is_read`);
ALTER TABLE `messages` ADD INDEX (`invitation_status`);
ALTER TABLE `model_categories` ADD INDEX (`type`);
ALTER TABLE `model_categories` ADD INDEX (`active`);
ALTER TABLE `pages` ADD INDEX (`type`);
ALTER TABLE `pages` ADD INDEX (`slug`);
ALTER TABLE `password_resets` ADD INDEX (`email`);
ALTER TABLE `sedcard` ADD INDEX (`image_type`);
#ALTER TABLE `sedcard` CHANGE `image_type` `image_type` INT(11) NOT NULL COMMENT '1=Portrait, 2=Full Body, 3=Fashion, 4=Beauty, 5=Favorite';
ALTER TABLE `posts` ADD INDEX (`verified_phone`);
ALTER TABLE `posts` ADD INDEX (`archived`);
ALTER TABLE `users` ADD INDEX (`active`);
ALTER TABLE `ltm_translations` ADD INDEX (`locale`);
ALTER TABLE `ltm_translations` DROP INDEX `locale`, ADD INDEX `locale` (`locale`, `group`) USING BTREE;
ALTER TABLE `ltm_translations` ADD INDEX (`key`);
ALTER TABLE `posts` ADD INDEX (`deleted_at`);
ALTER TABLE `users` ADD INDEX (`deleted_at`);
ALTER TABLE `favorites` ADD INDEX `wp_user_id` (`wp_user_id`, `wp_fav_id`) USING BTREE;
ALTER TABLE `blog_categories` ADD INDEX (`translation_of`);
ALTER TABLE `blog_categories` ADD INDEX (`wp_term_id`, `wp_parent_id`, `wp_translation_of`);
ALTER TABLE `blog_entries` ADD INDEX (`wp_post_id`, `wp_translation_of`);
ALTER TABLE `branches` ADD INDEX (`wp_category_id`, `wp_translation_of`, `wp_parent_id`);
ALTER TABLE `categories` ADD INDEX (`wp_term_id`, `wp_translation_of`, `wp_parent_id`);
ALTER TABLE `country_language` ADD INDEX (`wp_language`);
ALTER TABLE `valid_value_translations` ADD PRIMARY KEY (`id`);
ALTER TABLE `valid_value_translations` ADD INDEX (`valid_value_id`);
ALTER TABLE `valid_value_translations` DROP INDEX `valid_value_id`, ADD INDEX `valid_value_id` (`valid_value_id`, `locale`) USING BTREE;
ALTER TABLE `payments` ADD INDEX (`wp_post_id`, `wp_package_id`);
ALTER TABLE `valid_value_translations` ADD INDEX (`slug`);
ALTER TABLE `saved_posts` ADD INDEX (`wp_user_id`, `wp_post_id`);
ALTER TABLE `model_categories` ADD INDEX (`wp_category_id`, `wp_translation_of`, `wp_parent_id`);
ALTER TABLE `packages` ADD INDEX (`translation_lang`, `translation_of`);
ALTER TABLE `posts` ADD INDEX (`wp_post_id`);
ALTER TABLE `blog_tags_to_entries` ADD INDEX (`wp_entry_id`, `wp_tag_id`);

ALTER TABLE `messages` ADD INDEX (`message_type`);
ALTER TABLE `pages` ADD INDEX(`translation_lang`);
ALTER TABLE `pages` ADD INDEX(`excluded_from_footer`);
ALTER TABLE `pages` ADD INDEX(`active`);

ALTER TABLE `users` ADD INDEX (`featured`);
ALTER TABLE `pages` ADD `page_layout` ENUM('standard','custom') NOT NULL DEFAULT 'standard' AFTER `excluded_from_footer`;